### ISSUE TITLE
Template Puro Rio

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#1]
Te sumo un pedido de template para el restaurant, que vaya en la línea del de Rio Ancho, pero no el mismo. Con menor complejidad y más colorido.

**Comment by FAAREIA** [comment]
Ok, busco y les paso link

**Comment by LeandroBraier** [comment]
Fede, hoy mandame 3 posibles templates así avanzamos con esto, que está muy parado.

abrazo

**Comment by FAAREIA** [comment]
Ahi estuve viendo los templates, no encontré la gran cosa, pero paso links y pensá que todo se puede ajustar. Si hay cosas de extras, las podemos sacar también.

http://themeforest.net/item/dortoretto-html-theme/full_screen_preview/5625203
http://demo.yosoftware.com/?t=Berg-HTML
http://themeforest.net/item/cafe-slide-responsive-restaurant-html5-template/full_screen_preview/7842203
http://www.mediumra.re/attica/

**Comment by LeandroBraier** [comment]
Los veo con Eze y te doy feedback.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-09-03 17:08 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Seleccionaron este: http://demo.yosoftware.com/?t=Berg-HTML

Cierro el ticket y abro otro con el detalle.
