### ISSUE TITLE
Versión del Chat adaptada estéticamente para Río Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#10]
Necesitaría esto, en su versión estética. Mientras aprueban la versión estética la hacemos funcionar. Si está para el lunes todo bien, no es urgente. abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/menu2.html
Solo la estética
Dale F5

**Comment by FAAREIA** [comment]
Dale F5 otra vez

**Comment by LeandroBraier** [comment]
¿El color responde al fondo de la web? Porque me parece que sería mejor
usar el bordó que hay en la flor del logo.

Respecto de tipografías, es la misma que la fuente del texto de cada
sección no? Está buena pero ¿hay posibilidad de probar alguna otra?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, usé colores como los de la comida que se muestran, pero se puede probar lo que vos decis. El lúnes lo actualizo

**Comment by LeandroBraier** [comment]
Dale, no hay apuro.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, lo actualizarías porfa? Me gustaría poder mostrar la adaptación final en una reunión al mediodía. Usá el bordó, la tipografía dejala como está y después te doy feedback de última.

abrazo

**Comment by FAAREIA** [comment]
Fijate ahora Lea:
http://www.rioanchocolonia.com/menu2.html
F5

**Comment by LeandroBraier** [comment]
Me gusta, gracias! Entonces hoy lo veo con ellos (Marce y Deby) y ya vemos cómo lo implementamos. El de Benteveo ya está funcional, así que cuando me den el ok lo implementamos en ambos servidores. abrazo

**Comment by LeandroBraier** [comment]
Fede, cuando esté listo para publicar avisame, así te doy el mail efectivo al que habría que derivar todo.

abrazo

**Comment by FAAREIA** [comment]
Creo que ya esta andando y todo, se podría publicar en cualquier momento

**Comment by LeandroBraier** [comment]
Genial, Fede. Lo muestro y te doy el OK para subirlo.

Adonde redirige el mail ahora?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
la verdad no sé, pero creo que marce había puesto un mail que le habías dicho

**Comment by LeandroBraier** [comment]
Perfecto, entonces es el de Marcelo Susevich. Le voy a avisar directamente
por el chat entonces. Gracias-

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-07 9:47 GMT-03:00 Federico Arena notifications@github.com:
