### ISSUE TITLE
Requerimientos para Chat en Hosting Río Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#11]
Marce, me decís qué le tengo que pedir a Duplika para que podamos poner un chat igual al de Benteveo en el sitio de Río Ancho?

abrazo

**Comment by LeandroBraier** [comment]
Marce, al final en qué quedó esto? Me pasaste los requerimientos? No lo recuerdo. pasame y se lo pido a Duplika.

**Comment by mkreyness** [comment]
No lo habia visto.
Es un chat INDEPENDIENTE del de benteveo ? Los mails van a ir a otro lado ?
Porque si va a ser el mismo, no hace falta (ni conviene) instalar algo 
separado, es solo tener otro "cliente" de chat en la pagina de RioAncho, 
como ahora esta en la pagina de benteveo.com

**Comment by LeandroBraier** [comment]
El mail no va a ser el mismo pero si se puede usar todo el mismo sistema
mejor. El mail va a ser de @rioanchocolonia.com

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-04 12:23 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ok, entonces en principio en el sitio de rioancho propiamente dicho no 
hay que pedir nada.
Despues cuando arme Fede el cliente, le vamos a pasar un parametro en la 
llamada a lo que esta en chat.benteveo.tv, que sepa a quien tiene que 
mandarle el texto.
Internamente van a seguir pasando por robotchat@benteveo.tv, y cada 
cliente tomará lo que le corresponda de la casilla.
Esto que prioridad tiene ?

**Comment by FAAREIA** [comment]
rioanchocolonia.com/menu2.html
Aún no esta aprobado graficamente, pero sería igual al otro.

**Comment by LeandroBraier** [comment]
Gráficamente aprobado! Ya lo pueden implementar tranquilos.

El de Benteveo me funciona OK Fede, no lo saquemos.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Fede: ponelo todo igual que el de benteveo.tv, pero en vez de llamar a

chat.benteveo.tv/cgi-bin/chat.pl

que llame a

chat.benteveo.tv/cgi-bin/chatrio.pl

Y ojo donde le asigna "Benteveo" al globo, que diga "Rio Ancho" o algo asi.

Por ahora me va a mandar los mails a mi para probar, y si anda todo bien 
ya lo redirijo a la casilla definitiva.

**Comment by LeandroBraier** [comment]
Excelente, MK.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-04 18:08 GMT-03:00 mkreyness notifications@github.com:

**Comment by LeandroBraier** [comment]
No tan alta. Si está para el Jueves o Viernes está OK.

Vos decís que van a ir ambos a la misma casilla de mail? Sería mejor que
fueran a casillas separadas.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-04 13:24 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
Lo mio practicamente esta, es solo probarlo cuando Fede haga su
parte y despues ponerle la casilla definitiva, que no es la misma
que la de benteveo.
La que es la misma es la casilla INTERNA, a la que vos respondes,
pero es transparente, vos (o quien sea) simplemente responden lo que
les llega.

El 04/11/2014 a las 22:44,
  LeandroBraier escribió:

No tan alta. Si está para el Jueves o Viernes está OK.


  Vos decís que van a ir ambos a la misma casilla de mail? Sería
  mejor que

  fueran a casillas separadas.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-11-04 13:24 GMT-03:00 mkreyness
  <notifications@github.com>:


  > Ok, entonces en principio en el sitio de rioancho propiamente
  dicho no

  > hay que pedir nada.

  > Despues cuando arme Fede el cliente, le vamos a pasar un
  parametro en la

  > llamada a lo que esta en chat.benteveo.tv, que sepa a quien
  tiene que

  > mandarle el texto.

  > Internamente van a seguir pasando por robotchat@benteveo.tv,
  y cada

  > cliente tomará lo que le corresponda de la casilla.

  > Esto que prioridad tiene ?

  >

  > On 04/11/2014 12:40 p.m., LeandroBraier wrote:

  > > El mail no va a ser el mismo pero si se puede usar todo
  el mismo sistema

  > > mejor. El mail va a ser de @rioanchocolonia.com

  > >

  > > Leandro Braier

  > > Producción Audiovisual & Social Media

  > > Benteveo Producciones <http://benteveo.tv>

  > > Móvil 1158717399

  > >

  > > 2014-11-04 12:23 GMT-03:00 mkreyness
  <notifications@github.com>:

  > >

  > > > No lo habia visto.

  > > > Es un chat INDEPENDIENTE del de benteveo ? Los
  mails van a ir a otro

  > > lado ?

  > > > Porque si va a ser el mismo, no hace falta (ni
  conviene) instalar algo

  > > > separado, es solo tener otro "cliente" de chat en
  la pagina de

  > > RioAncho,

  > > > como ahora esta en la pagina de benteveo.com

  > > >

  > > > On 04/11/2014 09:38 a.m., LeandroBraier wrote:

  > > > >

  > > > > Marce, al final en qué quedó esto? Me pasaste
  los requerimientos? No

  > > > > lo recuerdo. pasame y se lo pido a Duplika.

  > > > >

  > > > > —

  > > > > Reply to this email directly or view it on
  GitHub

  > > > > <

  > > >

  > >

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61633491
      > > > >.

```
  > > > >

  > > >

  > > > —

  > > > Reply to this email directly or view it on GitHub

  > > >

  > > <

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61655721
      > >

```
  > > > .

  > > >

  > >

  > > —

  > > Reply to this email directly or view it on GitHub

  > > <

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61658775
      > >.

```
  >

  > >

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61666530
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto, Marce. Entendido. abrazo

**Comment by FAAREIA** [comment]
Ahi esta puesto el script que llama al .pl de chat.benteveo
Lo que si, puse el script en un archivo JS, si no funciona habría que
hacerlo andar. Cuando se optimice algo, o haya algun agregado, va a  ser
más simple.
Ojo que también puede no andar si te rechazan la llamada cross-domain

2014-11-04 23:53 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by mkreyness** [comment]
```
En que URL lo puedo probar ?
De la llamada cross-domain ya me ocupe yo, al hacer el chatrio.pl
Si llamas al chat.pl, no va a funcionar.
Hace todo IGUAL que en el otro por favor, excepto poner chatrio.pl,
para poder probarlo, porque ademas me manda los mails a mi.
Una vez que ANDE probamos de hacer ese cambio de lugar de cosas.
Si no lo invoca nunca, no puedo probar nada.

El 05/11/2014 a las 10:17, Federico
  Arena escribió:

Ahi esta puesto el script que llama al .pl de
  chat.benteveo

  Lo que si, puse el script en un archivo JS, si no funciona habría
  que

  hacerlo andar. Cuando se optimice algo, o haya algun agregado, va
  a ser

  más simple.

  Ojo que también puede no andar si te rechazan la llamada
  cross-domain


  2014-11-04 23:53 GMT-03:00 LeandroBraier
  <notifications@github.com>:


  > Perfecto, Marce. Entendido. abrazo

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61752423
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
La URL es la misma que antes, menu2.html
Ahi ya le puse el script inline

**Comment by mkreyness** [comment]
```
Esta mal escrita la linea que llama a chatrio.pl, le faltan cosas.
Por favor ponela IGUAL que la del chat de benteveo, lo UNICO que
tiene que cambiar es que diga chatrio.pl en vez de chat.pl
El resto tiene que estar IDENTICO.

El 05/11/2014 a las 11:46, Federico
  Arena escribió:


  La URL es la misma que antes, menu2.html
    Ahi ya le puse el script inline
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahi lo arreglé

**Comment by mkreyness** [comment]
```
sigo viendolo mal, ya di F5, ctrl-F5, todo y sigue diciendo

"http://chat.benteveo.tv/cgi-bin/chatrio.pl" + id + "&quien=" +
quien.value + "&txt=" + baktexto

cuando debe decir:

"http://chat.benteveo.tv/cgi-bin/chatrio.pl?id=" + id +
"&quien=" + quien.value + "&txt=" + baktexto

El 05/11/2014 a las 12:11, Federico
  Arena escribió:

Ahi lo arreglé


  El 5 de noviembre de 2014, 11:54,
  mkreyness<notifications@github.com>

  escribió:


  >

  >

  >

  >

  >

  > Esta mal escrita la linea que llama a chatrio.pl, le faltan
  cosas.

  > Por favor ponela IGUAL que la del chat de benteveo, lo UNICO
  que

  > tiene que cambiar es que diga chatrio.pl en vez de chat.pl

  > El resto tiene que estar IDENTICO.

  >

  > El 05/11/2014 a las 11:46, Federico

  > Arena escribió:

  >

  >

  > La URL es la misma que antes, menu2.html

  > Ahi ya le puse el script inline

  >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61818470
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
Ahi lo volvi a subir, y lo rechequié.

**Comment by mkreyness** [comment]
```
pero ahora le pusiste chat.pl de nuevo !!!
tiene que ser chatrio.pl, por favor fijate lo que puse aca abajo,
eso es lo correcto.

El 05/11/2014 a las 12:30, Federico
  Arena escribió:

Ahi lo volvi a subir, y lo rechequié.


  El 5 de noviembre de 2014, 12:20,
  mkreyness<notifications@github.com>

  escribió:


  >

  >

  >

  >

  >

  > sigo viendolo mal, ya di F5, ctrl-F5, todo y sigue diciendo

  >

  > "http://chat.benteveo.tv/cgi-bin/chatrio.pl" + id +
  "&quien=" +

  > quien.value + "&txt=" + baktexto

  >

  > cuando debe decir:

  >

  > "http://chat.benteveo.tv/cgi-bin/chatrio.pl?id=" + id +

  > "&quien=" + quien.value + "&txt=" + baktexto

  >

  > El 05/11/2014 a las 12:11, Federico

  > Arena escribió:

  >

  > Ahi lo arreglé

  >

  >

  > El 5 de noviembre de 2014, 11:54,

  > mkreyness<notifications@github.com>

  >

  > escribió:

  >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > > Esta mal escrita la linea que llama a chatrio.pl, le
  faltan

  > cosas.

  >

  > > Por favor ponela IGUAL que la del chat de benteveo, lo
  UNICO

  > que

  >

  > > tiene que cambiar es que diga chatrio.pl en vez de
  chat.pl

  >

  > > El resto tiene que estar IDENTICO.

  >

  > >

  >

  > > El 05/11/2014 a las 11:46, Federico

  >

  > > Arena escribió:

  >

  > >

  >

  > >

  >

  > > La URL es la misma que antes, menu2.html

  >

  > > Ahi ya le puse el script inline

  >

  > >

  >

  > > —

  >

  > > Reply to this email directly or view

  >

  > > it on GitHub.

  >

  > >

  >

  > > —

  >

  > > Reply to this email directly or view it on GitHub

  >

  > >

  > <

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61818470
      > >

```
  > > .

  >

  > >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/11#issuecomment-61822769
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by FAAREIA** [comment]
ahora, ahora ahora
si
jajajajajaj, que desastre

**Comment by mkreyness** [comment]
Listo, ya anda.
Lo que si sacale el "Lorem ipsum" que sobra. No tendria que verse ningun 
globo del usuario hasta que tipee algo.
Lean: que direccion de mail pongo para que lleguen los mails entonces ? 
Por ahora esta con la mia.

**Comment by FAAREIA** [comment]
ya esta lo de ipsum

**Comment by LeandroBraier** [comment]
Gracias! Redireccionalo por ahora a ms@benteveo.tv Cuando esté hecho
avisame.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-05 13:47 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Esperen, ahi puse el script en un .js
Marce probá si ahora anda igual

**Comment by mkreyness** [comment]
Listo, ojo que no se si las limpiezas de HTML etc funcionan con 
cualquier cliente, las pruebas que yo hice fueron con gmail.
Si MS usa algun otro, habria que chequearlo.

**Comment by FAAREIA** [comment]
Marce, probaste con tu email el cambio que hice? Puse el script en un archivo js.

**Comment by mkreyness** [comment]
No, ahora repongo el mio y veo.

**Comment by mkreyness** [comment]
Anduvo perfecto, repongo a MS.
