### ISSUE TITLE
Maquetación Página Lodge

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#12]
Fede, necesito que maquetes una nueva página para la web de Río Ancho: se llama Lodge. Es para mostrar las habitaciones. Seguí el modelo de esta:

http://awasiatacama.com/en/our-lodge/rooms

Va con planitos y todo.

Las habitaciones son 3:

Habitación Deluxe
Habitación Junior Suite
Habitación Master Suite

abrazo

**Comment by FAAREIA** [comment]
Ok, los planos y eso los tenes?

**Comment by LeandroBraier** [comment]
No, todavía no. Usá capturas de Awasi Atacama por ahora.

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/lodge.html

**Comment by LeandroBraier** [comment]
Perfecto, lo paso para aprobar. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, te subí a la carpeta RIO ANCHO MAQUETADOR 2 fotos por cada habitación (hay unas secundarias en una de las habitaciones pero quedan para más adelante).

Además, subí dos fotos, una del frente de Rio Ancho y otra de otro ambiente muy lindo del mismo. Las dos son para reemplazar las fotos 2 y 4 (en orden de aparición) de la sección Filosofía. La 0134 reemplaza a la foto 2 y la 0140 reemplaza a la 4.

Cuando las tengas subidas pasame el link de la versión previa así la hago aprobar con el equipo.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, ya esta actualizado.
http://www.rioanchocolonia.com/lodge.html
F5 que reemplacé fotos.

**Comment by LeandroBraier** [comment]
Perfecto las fotos de las habitaciones.

Las otras dos fotos no las pusiste donde te pedí. Era en la sección
Filosofía en lugar de las fotos 2 y 4. Las dos que estaban en Lodge deben
quedar las que estaban antes.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahora si, dale F5

**Comment by LeandroBraier** [comment]
Perfecto. Una cosita solamente: no queda del todo bien la foto larga de la
habitación Deluxe. Te acabo de subir una versión un poco más corta (no en
el mismo formato que las otras, porque no queda bien, pero más disimulada
la diferencia). Faltaría reemplazar esa entonces.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Entiendo lo que decis, pero no sería mejor hacerlo una vez qe tengamos en contenido? Capas que el texto termina siendo largo y la foto lo acompaña. ¿Que decis?

**Comment by LeandroBraier** [comment]
Ok, me parece bien. No hay apuro para esto. Lo que te pasé de la landing
del nuevo casting si es urgente. Chequealo porfa:
https://github.com/LeandroBraier/BenteveoTV/issues/27

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-20 9:51 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, en carpeta RIO ANCHO MAQUETADOR te subí los 3 planitos de cada habitación.

Están con un fondo marrón y también con fondo transparente. FIjate cómo te sirven mejor.

Abajo te paso los textos que van en cada habitación:

Master Suite

Superficie 75 M2
Habitación con cama Matrimonial o dos camas twin.
Control Solar Motorizado
Televisor LCD HD de 50"
Aire Acondicionado
Sala de estar separado
Posibilidad de hasta 2 huéspedes adicionales
Balcón privado con Jacuzzi y vista panorámica al Rio de la Plata y al monte autóctono

Junior Suite

Superficie 63 M2
Habitación con cama Matrimonial o dos camas twin.
Vistas a la piscina, el monte autóctono y el Rio de la Plata
Control Solar Motorizado
Televisor LCD HD de 50"
Aire Acondicionado
Jardín privado con ducha exterior y área de relax
Baño compartimentado

Deluxe

Superficie 30 M2
Habitación con cama Matrimonial o dos camas twin.
Vistas a la piscina, el monte autóctono y el Rio de la Plata
Posibilidad de 1 huésped adicional
Televisor LCD HD de 50"
Aire Acondicionado
Baño compartimentado

Llegás a subirlo para hoy?

**Comment by LeandroBraier** [comment]
No lo cierres, cuando tengas el link me lo pasás por acá.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, no se cuando lo cerré =/  pero ahi va el link:
http://www.rioanchocolonia.com/lodge.html
Dale F5

**Comment by LeandroBraier** [comment]
Gracias Fede!

Fijate como lo veo. Se me superpone el texto con el plano. Además un pequeño pedido más:

necesito que enroques las fotos de la junior suite y la deluxe. Te las pasé al revés yo.

![captura de pantalla 2014-11-26 a la s 10 31 52](https://cloud.githubusercontent.com/assets/6719872/5201940/213c5ebe-7557-11e4-8738-3d62aff2b2d4.png)

**Comment by FAAREIA** [comment]
Hola Lea, si aún no esta hecho lo responsivo. Miralo en un monitor más grande y vas a ver q no se cruza.
Una vez aprobado lo ajusto para lo rsponsivo

**Comment by FAAREIA** [comment]
Dale F5 por las fotos

**Comment by LeandroBraier** [comment]
Gracias Fede! Le di Full Screen y lo vi bien. Lo mando para aprobación.

Aprovecho a avisarte: te vamos a pedir algo de maquetación de Siguit, sería una página web con formularios sucesivos para iPad, en la línea de lo que hiciste de apuro el jueves pasado pero más largo y con más botones.

Seguramente te pase el diseño el viernes para que tengamos las primeras pantallas el martes de la semana siguiente. Por las dudas te aviso para que lo vayas organizando. Te vamos a pasar los PSDs con la info y el diseño final, vos lo maquetás y Marce K hace la parte de programación funcional, que ya la está haciendo, estilo como hicimos con Dánica.

abrazo

**Comment by LeandroBraier** [comment]
Fede, te voy a pasar hoy más tarde nuevas versiones de los planos, porque a MS no le gustaron. Más allá de eso, te pido un cambio de fotos:
1. De las dos fotos que ahora hay en Junior suite, quitá la primera.
2. La foto vertical del baño que hay en Deluxe pasala a Master Suite
3. Ahora que quedan 1 foto en Deluxe y 1 foto en Junior Suite, volvé a enrocarlas (es decir, cambiarlas de una habitación a la otra)

Apenas tenga los nuevos dibujos de planta te los paso.

abrazo

**Comment by LeandroBraier** [comment]
Ya te las subí a las plantas. Las tenés en la carpeta de PLANOS HABITACIONES dentro de RIO ANCHO MAQUETADOR/Fotos Lodge/.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, fijate ahi
http://www.rioanchocolonia.com/lodge.html

**Comment by LeandroBraier** [comment]
Están OK!

Avancemos con la versión responsive porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, fijate ahora dale F5

**Comment by LeandroBraier** [comment]
Quedó OK Fede!

Lo que me acabo de dar cuenta es que el texto en negro no va. Quitalo, que
quede sólo el texto en rojo.

Con eso estamos calculo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Fijate ahora, avisame cuando este al 100% asi lo dejamos online

**Comment by LeandroBraier** [comment]
Perfecto. Subila ya y se las mando con Lodge online.

Hasta qué hora te podemos pedir cosas hoy? Seguro me pidan pequeños
detalles más de Rio Ancho porque estan con un evento importante de agencias
de turismo el fin de semana.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, hasta las 13hs.
Dependiendo el día le doy de 8:30 a 12:30 o de 9:00 a 13:00

**Comment by FAAREIA** [comment]
Ahi subi la seccion Lodge

**Comment by LeandroBraier** [comment]
Fede, último detalle por ahora en la página Lodge. De la misma forma que subiste el FotoBook digital, subí el Brochure Digital que te envié por WeTransfer en la página Lodge.

https://www.wetransfer.com/downloads/96c13abf946d2f5689d3ed58b4a67dae20141205185156/698945

Puede ser mañana

abrazo

**Comment by LeandroBraier** [comment]
Fede, modificaciones en la página Lodge para que hagas para la semana que viene. 

1) Subí el Brochure Digital que te paso en link de Dropbox. Que vaya al pie de la página, de la misma forma que subiste el FotoBook, pero que aparezca solo en la Página Lodge y al pie, no en el header.

https://www.dropbox.com/s/a6vui2x7w2diuhl/Brochure%20Digital%20Rio%20Ancho.pdf?dl=0

2) Reemplazá los textos actuales por los siguientes:

Habitación Deluxe
•Superficie 30 M2
•Televisor LCD HD de 50"
•Aire Acondicionado
•Vistas a la piscina, el monte autóctono y el Rio de la Plata •Habitación con cama Matrimonial o dos camas twin •Posibilidad de 1 huésped adicional
•Baño compartimentado

Habitación Junior Suite
•Superficie 63 M2
•Control Solar Motorizado
•Televisor LCD HD de 50"
•Aire Acondicionado
•Vistas a la piscina, el monte autóctono y el Rio de la Plata •Habitación con cama Matrimonial o dos camas twin •Jardín privado con ducha exterior y área de relax
•Baño compartimentado

Habitación Master Suite
•Superficie 75 M2
•Control Solar Motorizado
•Televisor LCD HD de 50"
•Aire Acondicionado
•Habitación con cama Matrimonial o dos camas twin
•Sala de estar independiente (con posibilidad de dos huéspedes adicionales)
•Balcón privado con Jacuzzi y vista panorámica al Rio de la Plata y al monte autóctono •Baño compartimentado

CONFIRMAME RECEPCIÓN PORFA.

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/__nuevo/lodge.html

**Comment by LeandroBraier** [comment]
Impecable, Fede. Solo fijate que el Baño Compartimentado de la Master Suite quedé una línea más abajo, solo. El resto. Perfecto. Subilo nomás. abrazo

**Comment by FAAREIA** [comment]
Ya esta listo. recien subí todo.
Si se aprueba todo mejor. No tengo por separado las actualizaciones del sitio. Sino te volves loco

**Comment by LeandroBraier** [comment]
Entiendo. Tenés mi OK para subirlo todo Fede. A lo sumo habrá cambios pero no desaprobaciones. abrazo
