### ISSUE TITLE
Implementar Multilenguaje

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#13]
Fede, necesito que implementes la opción en la página para que se pueda ver en varios idiomas, por lo menos 3: español, inglés y francés.

Cuando tengas la parte maquetada yo te paso los contenidos traducidos. abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/lodge.html

**Comment by LeandroBraier** [comment]
Fede, ya está todo listo entonces para cargar las traducciones de los textos?

**Comment by LeandroBraier** [comment]
Hay un CMS o algo donde cargarlas?

**Comment by FAAREIA** [comment]
No, es todo a mano...
Si queres pasame los textos y voy duplicando los HTML
Eso, si, un cambio que haya que hacer y hay que multiplicarlo por 3

**Comment by LeandroBraier** [comment]
Entiendo. Yo me ocupo de pasarte todo de la mejor manera. En qué formato lo querés? TXT en UFT8 o cómo preferís que te los pase para que sea más sencillo?

**Comment by FAAREIA** [comment]
Cualquier forma de archivo de texto esta OK

**Comment by LeandroBraier** [comment]
Fede, ya tengo la versión en inglés del sitio de Río Ancho. Apenas tengas un hueco subila.

El archivo de texto está en RIO ANCHO MAQUETADOR. Se llama: Traducción al Inglés del Sitio Rio Ancho

abrazo

**Comment by FAAREIA** [comment]
Faltaría traducir:

Meta keywords
Meta descriptions

**Reservas**
Gracias por solicitarnos tu reserva en Río Ancho Gourmet Lodge. Revisá tu casilla de email para confirmar el proceso. ¡Te esperamos!

**Programas** - Frases HTML que aparecen si no carga una imagen:
"Almuerzo mirando al Río de la Plata"
"Té con vista al bosque"
"Atardecer y tragos con vista al Río"
"Cena Gourmet en Colonia"
"Tazas de cerámica"
"Living del Lodge"

**Contacto**
Para elegir la ruta u otro punto de partida haga click en "Más opciones"

**Chat**
¿Se va a traducir?
Además de lo que se puede ver online, habría que traducir los mensajes de error que maneja Marce K. desde el sistema.

**Textos version mobile solamente**
No vi que los tradujeran.

Ya esta online en http://www.rioanchocolonia.com/__nuevo/

**Comment by LeandroBraier** [comment]
Perfecto. Subí lo que tenemos por ahora. Para tu vuelta te paso las traducciones faltantes. abrazo y felices vacaciones más que merecidas Fede!!! Muy felices fiestas!

**Comment by FAAREIA** [comment]
Gracias Lea! Felices fiestas para ustedes también, pasenla bien y a despejarse y un poco!
Abrazooooooooooo
(ya esta todo subido)

**Comment by LeandroBraier** [comment]
Fede, van los textos que me pedías. Como el chat no va más en Río Ancho por ahora, no te paso esos textos.

Meta keywords
Meta descriptions

Descripción: 

Rio Ancho, Gourmet Lodge, is a gourmet restaurant with accommodation in an exclusive lodge. It is located in a rural area 10 km far from the historical center of Colonia del Sacramento along De la Plata river.

metatags: 

colonia, uruguay, hotel, restaurant, lodge, río de la plata

Reservations
Gracias por solicitarnos tu reserva en Río Ancho Gourmet Lodge. Revisá tu casilla de email para confirmar el proceso. ¡Te esperamos!

Thanks for requesting a reservation at Rio Ancho Gourmet Lodge. Please check out your inbox to confirm the process. See you soon!

Programas - Frases HTML que aparecen si no carga una imagen:
"Almuerzo mirando al Río de la Plata"
"Té con vista al bosque"
"Atardecer y tragos con vista al Río"
"Cena Gourmet en Colonia"
"Tazas de cerámica"
"Living del Lodge"

"Lunch overlooking the river"
"Tea with a view to the forest"
"Sunset and drinks overlooking the River"
"Gourmet Dinner in Colonia"
"Ceramic Mug"
"Lodge Living Room"

Contacto
Para elegir la ruta u otro punto de partida haga click en "Más opciones"

To choose the route or another point click "More Options"

Chat
¿Se va a traducir? POR AHORA NO.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo Lea, ojo que las meta-description y las meta-keywords que me enviaste son únicas.
Lo correcto sería que me enviar las meta-description y meta-keywords de cada HTML, sino a los buscadores no les gusta ver esos textos repetidos

**Comment by LeandroBraier** [comment]
Dale, pasame las lista de nombre de cada HTML o lo meta actuales y te lo
mando.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-08 17:50 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
HOME
`<meta name="description" content="Rio Ancho, Gourmet Lodge, es un restaurant gourmet con alojamiento en un exclusivo lodge que se emplaza en una zona rural a 10 km del Centro Histórico de Colonia del Sacramento y a orillas del Río de la Plata.">`
`<meta name="keywords" content="Colonia, Uruguay, Hotel, Restaurant, Río de la Plata">`

CARTA
`<meta name="description" content="El menú de Rio Ancho Gourmet Lodge está concebido agasajar mediante un momento mágico. Es un menú experiencia de siete pasos, inspirados en lo mejor que nos puede brindar la estacionalidad, las huertas, los paisanos, los pescadores de este paraje en la costa de Colonia, Uruguay.">`
`<meta name="keywords" content="Menú, Estación, Huerta, Pescadores, Uruguay">`

RESERVAS
`<meta name="description" content="Hacé tus reservas para cualquier cantidad de personas en cualquiera de nuestros programas. Rio Ancho Gourmet Lodge se emplaza en una zona rural a 10 km del Centro Histórico de Colonia del Sacramento y a orillas del Río de la Plata.">`
`<meta name="keywords" content="Reservas, Río ancho, Gourmet lodge, Uruguay">`

PROGRAMAS
`<meta name="description" content="Organizamos la experiencia de Río Ancho Gourmet Lodge en distintos programas: Almuerzo + Distensión, Tardes + Té, Atardeceres + Cocktails + Cena + Lodge + Desayuno, Programas de Contenido y Eventos corporativos y sociales.">`
`<meta name="keywords" content="Almuerzo, Merienda, Cena, Cocktails, Desayuno, Eventos">`

RÍO ANCHO
`<meta name="description" content="De todos los momentos inolvidables vividos en familia y entre amigos, a lo largo de los años nace Rio Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Rio de la Plata. La visión franca desde Colonia, Uruguay a este inmenso río es nuestro sello. Te invitamos a disfrutar del amplio horizonte, compartir la alegría de cuidar y enriquecer un pedazo de este planeta.">`
`<meta name="keywords" content="Río Ancho, Gourmet lodge, Filosofía, Uruguay">`

LODGE
`<meta name="description" content="De todos los momentos inolvidables vividos en familia y entre amigos, a lo largo de los años nace Rio Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Rio de la Plata. La visión franca desde Colonia, Uruguay a este inmenso río es nuestro sello. Te invitamos a disfrutar del amplio horizonte, compartir la alegría de cuidar y enriquecer un pedazo de este planeta.">`
`<meta name="keywords" content="Río Ancho, Gourmet lodge, Filosofía, Uruguay">`

CONTACTO
`<meta name="description" content="Escribinos tus inquietudes directamente aquí. Dirección: Tula Suarez de Cutinella s/n, Paraje El Caño, Colonia del Sacramento. Teléfono: +598 4520 2205">`
`<meta name="keywords" content="Río Ancho, Gourmet lodge, Contacto, Dirección, Teléfono">`
