### ISSUE TITLE
Cambiar nombre del "Menu" por término "Carta"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#14]
Solo eso. Es el nombre de la página en particular llamada "Menú"

**Comment by FAAREIA** [comment]
En todos los lados donde diga "Menú" le pongo "Carta"?

**Comment by LeandroBraier** [comment]
No, solo en el nombre de la sección.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-07 9:23 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ok, lo cambió en el Menú del sitio y en el title de la página

**Comment by LeandroBraier** [comment]
Exacto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi ya lo cambié, ni bien subamos el chat actualizó todo junto

**Comment by LeandroBraier** [comment]
Ok, no problem.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
