### ISSUE TITLE
Agregar CC a mails de form de contacto y chat

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#15]
Fede, necesitaría que agregues, tanto a los mails que dispara el formulario de contacto y el chat un CC, es decir, que se envían con copia a db@rioanchocolonia.com.

Actualmente están llegando solo a ms@rioanchocolonia.com, verdad?

**Comment by FAAREIA** [comment]
Hola Lea, lo del chat lo maneja Marce. Lo del formulario de contacto ahora veo, capas que necesite a marce también.

**Comment by FAAREIA** [comment]
Actualmente llegan a:
contactorioanchocolonia@gmail.com

**Comment by mkreyness** [comment]
De todos modos me parece peligroso que el chat vaya a mas de una 
direccion, porque podrian contestar desde ambas distintas cosas y sonar 
rarisimo para el que esta del otro lado.
Una seria solo para backup ?

**Comment by LeandroBraier** [comment]
Hagamos lo que piden, después vemos.

Pero me estás diciendo que los formularios no llegan a ms@rioanchocolonia?

Yo te lo había pedido te acordás?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-18 14:20 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
Las reservas van a ms@rioancho...
Contacto no lo cambié en su momento, lo cambió ahora

**Comment by LeandroBraier** [comment]
Ah, ok. Cambialo porfa.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Listo lo del mail principal y el CC en el formulario de contacto

**Comment by mkreyness** [comment]
El chat esta yendo a ms@benteveo.tv.
Confirmame las dos direcciones a que deberia ir entonces.

**Comment by LeandroBraier** [comment]
Excelente. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Marce, dejemoslo así al chat por ahora. Que siga redirigiendo a
ms@rioanchocolonia.com

Estamos bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Pero te repito que nunca lo hizo, el chat manda a ms@benteveo.tv, lo 
cambio entonces ?

**Comment by FAAREIA** [comment]
Aclaro que el chat aún no esta online, solamente esta en esa página de prueba.

**Comment by LeandroBraier** [comment]
Sisi, lo recuerdo. Hagamos así:

MK, redigigilo a ms@rioanchocolonia.com

Después de hecho eso, lo damos de alta en la página de Río Ancho. Ya tengo
el OK.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
Listo lo mio.

**Comment by FAAREIA** [comment]
El chat ya esta subido en todas las secciones

**Comment by LeandroBraier** [comment]
Genial. Ahi lo veo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-19 11:54 GMT-03:00 Federico Arena notifications@github.com:
