### ISSUE TITLE
Duplicación del Logo

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#16]
Fede, veo duplicado y cortado el logo en el sitio online. No es un tema de resoluciones, me pasa en todas.

Adjunto capturas
![captura de pantalla 2014-11-19 a la s 09 46 48](https://cloud.githubusercontent.com/assets/6719872/5105915/2afa9c12-6fd1-11e4-9848-c9a6ab6b6d6b.png)
![captura de pantalla 2014-11-19 a la s 09 46 55](https://cloud.githubusercontent.com/assets/6719872/5105919/32be9214-6fd1-11e4-91a8-1bafbee71383.png)

**Comment by FAAREIA** [comment]
Ahi esta como antes, ahora las banderas estan en SVG porque ese modelo no lo conseguia en tamaño más grande

**Comment by LeandroBraier** [comment]
Recién entré y lo sigo viendo igual al logo, puede ser?

Le di refresh.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si, ahi lo actualicé

**Comment by LeandroBraier** [comment]
Perfecto, gracias!
