### ISSUE TITLE
Newsletter Río Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#17]
Buen día Fede, tengo una imagen para embeber en un newsletter de Río Ancho.

Marce me la pidió ayer tarde y como estabas a full con lo de Siguit no te quise molestar. Mandé a diseñar la imagen pensando que yo iba a poder armar el html pero no pude. El pedido es simple: armar el newsletter con esta imagen:

https://www.dropbox.com/s/i70azt2odi1g6s3/Conoc%C3%A9-R%C3%ADo-Ancho-Gourmet-Lodge.jpg?dl=0

Enviamela y vemos qué dice Marce S. Estoy seguro que va a decir que la letra es chiquita y no se lee, así que si podés ir trabajando eso después de la primera versión genial, pero necesito mandar la primer versión del html con la imagen tal como está.

Te paso el editable en illustrator de la imagen para que lo puedas adaptar. Creo que se puede estirar hacia abajo sin problemas. De última le agregás fotos a los costados de las de Río Ancho que tenés para la web.

https://www.dropbox.com/s/68yd9er20nc587o/newsletter.pdf?dl=0

Confirmame apenas puedas ver esto por si tenés alguna duda. Gracias!

**Comment by LeandroBraier** [comment]
La idea del html es igual a la del mail del Casting que hiciste anteayer, no te mates más que eso. Con ese mismo sistema le metés la imagen subida al servidor de Benteveo, con link a la web de Río Ancho Colonia en la imagen, más el link para ver en el navegador. No te compliques más que eso.

abrazo

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/mailing/conoce-rio-ancho/conoce-rio-ancho.html

Ahora hago otra versión adelantandonos a la letra chica, no?

**Comment by LeandroBraier** [comment]
Si, porfa. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-21 9:12 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.benteveo.tv/mailing/conoce-rio-ancho/conoce-rio-ancho.html
Si bien no dijeron nada aun, ya lo subí

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/mailing/conoce-rio-ancho/conoce-rio-ancho.html
Lo subi al server correspondiente

**Comment by LeandroBraier** [comment]
Perfecto, Fede! Gracias!

No me dijo nada más Marce, pero a Deby le gustó. Cualquier novedad yo te
aviso. Quedó excelente.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
esto quedó resuelto por ahora. abrazo
