### ISSUE TITLE
Corrección en Reservas 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#18]
Fede, me pasaron un par de detalles a corregir en el sitio

RESERVAS

 Por default esta mostrando la Fecha 13 de Junio, debería ser la fecha de hoy.

Lo otro que pidió Marce dejame que lo vea yo por mi lado antes de pedirte el cambio.

abrazo

**Comment by LeandroBraier** [comment]
1. Agregá una opción más en los programas que sea "Cena" así a secas. Esa debería ser la opción que aparezca por default. No borres la que dice "Cena + Lodge + Desayuno". Esa dejala así como está.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo

**Comment by LeandroBraier** [comment]
Gracias Fede!
