### ISSUE TITLE
Modificaciones Textos Sección Filosofía

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#19]
Fede, para que hagas entre hoy y mañana, sin apuro, van correcciones a los textos actuales de la página de Río Ancho.

SECCIÓN RÍO ANCHO
1. Cambiar el párrafo actual que comienza con "De todos los momentos inolvidables…. hasta: … un pedazo de este planeta" por el siguiente texto:

"De un horizonte de vivencias inolvidables nace Rio Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Rio de la Plata y a pocos kilómetros de Colonia del Sacramento, Uruguay, la visión franca a este inmenso río es nuestro sello. Te invitamos a disfrutar de atardeceres únicos, playa privada y el silencio propio del lugar. La naturaleza alrededor invita a disfrutar, pasear y contemplar desde todos los espacios de la casa."
1. Cambiar la palabra "convertido" en la sección de Martin Molteni por "transformando".

abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/

**Comment by LeandroBraier** [comment]
Perfecto, gracias!
