### ISSUE TITLE
Modificaciones Textos Sección Carta

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#20]
Me pidieron cambiar los textos que se sobreimprimen sobre cada foto.

Rio Ancho Gourmet Lodge abre sus puertas para honrar a sus huéspedes. 
La magia de nuestra cocina se inspira en lo mejores frutos que brindan nuestros productores locales. Sus huertas, carnes, quesos y pesca son convocados para ofrecer un menú de siete pasos. 

El menú de Rio Ancho Gourmet Lodge, es un recorrido entre los mejores productos nativos y exóticos que hemos encontrado en la región y una experiencia única en el lugar. Nuestra propuesta privilegia tanto a comensales vegetarianos como omnívoros. Son todos bienvenidos a nuestra mesa.

El camino comienza con un aperitivo y nuestros panes amasados día a día, luego seguimos con la sopa crema que nos prepara para recibir el tercer paso: la entrada. 

Con el deseo de seguir descubriendo texturas; seguirá la pesca de río y la pasta casera, con el quinto paso llegamos a una carne o vegetales exquisitamente preparados. 
El dulce, sugerente, y un final con infusiones o cafe, acompañados de petit fours. 

Nuestra propuesta contempla vino y bebidas. Rio Ancho cuenta con una cava especial para descubrir los vinos que Uruguay tiene para ofrecer y sorprender.

abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/carta.html

**Comment by LeandroBraier** [comment]
Joya, gracias!
