### ISSUE TITLE
Pequeña modificación Texto Sección Filosofía

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#21]
Va un pequeño cambio pedido por el cliente:

"De un horizonte de vivencias inolvidables nace… ubicado en un entorno único, a orillas del Rio de la Plata, a pocos km de Colonia del Sacramento, Uruguay. La visión franca a este inmenso río es nuestro sello. Te invitamos a disfrutar de atardeceres únicos, playa privada y el silencio propio del lugar. La naturaleza alrededor invita a disfrutar, pasear y contemplarla desde todos los espacios de la casa."

Sin apuro.

**Comment by FAAREIA** [comment]
Ahi esta listo

**Comment by LeandroBraier** [comment]
Los puntos suspensivos ponelos tal como está ahí porfa, me lo pidieron así.

**Comment by FAAREIA** [comment]
Pensé que era una continuación, ahi lo puse bien:
http://rioanchocoloniacom/index2.html

**Comment by LeandroBraier** [comment]
Así está bien. Dejame que lo confirme y estamos.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Ahora sí va versión final, Fede. Cuando lo puedas impactar ya estamos:

De un horizonte de vivencias inolvidables nace Río Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Rio de la Plata y a pocos km de Colonia del Sacramento, Uruguay. La visión franca a este inmenso río es nuestro sello, una invitación a disfrutar de atardeceres únicos, playas de arenas blancas, el silencio propio del lugar y una naturaleza que puede contemplarse desde todos los espacios de la casa.

**Comment by LeandroBraier** [comment]
Me pidieron una modificación más, te la edité en el comentario anterior. Quedó así ya.

**Comment by FAAREIA** [comment]
Fijate ahora.

**Comment by LeandroBraier** [comment]
Perfecto. Subilo online al sitio nomás.

abrazo
