### ISSUE TITLE
Subir FotoBook Digital Rio Ancho Descargable

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#22]
Fede, porfa sumale un link al lado de redes sociales que permita descargar este fotobook. 

https://www.dropbox.com/s/iw5jtras8v5twxv/FotoBook%20Rio%20Ancho%20Gourmet%20Lodge.pdf?dl=0

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, avisa si esta ok: http://www.rioanchocolonia.com/index2.html
Dale F5

**Comment by LeandroBraier** [comment]
Hay posibilidad de que se vea como si fuera en Google Drive? Así ponemos la
opción de VER y DESCARGAR.

La de VER se vería la presentación como en Google Drive. La de DESCARGAR se
descargaría como ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Me parece medio complejo para un simple link.
Si se ve online, el mismo navegador puede abrirlo hoy en día. (es la acción por defecto)
Si queres que se vea como google drive, ya hay que meter un plugin y probarlo.

**Comment by LeandroBraier** [comment]
No hace falta que sea por Google Drive, ponelo que se vea online entonces.
No hay problema. Aunque tengas que comprimir un poco la calidad de las
imágenes.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-28 15:48 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/index2.html
Ahi le saque lo del download y le baje el peso al PDF en 5mb
;)

**Comment by LeandroBraier** [comment]
Gracias! Igual te la había pedido las dos: VER y también DESCARGAR.

En particular este VER debería verse en la resolución de pantalla de cada
navegador, no? Sino queda demasiado grande.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No había entendido.
Ahi va como queda con 2 links, para mi se complejiza sin necesidad:
http://www.rioanchocolonia.com/index2.html

Con respecto al PDF, cada navegador lo abre pero imagino que c/u tendrá configuraciones de visualizacion diferentes. Aca en FF el ancho lo ocupa al 100%

**Comment by LeandroBraier** [comment]
Dejalo así por ahora, solo corregí el texto de "Descargar" reemplazandolo
por "Descargalo". Y listo, seguimos con SIGUIT.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-11-28 16:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi esta listo, fijate que lo pase de "Descarglo" a "Descargar", creo que eso era lo que querías.

**Comment by LeandroBraier** [comment]
Perfecto, subilo a producción nomás.

abrazo

**Comment by FAAREIA** [comment]
Subido y de paso corregí algo que vi

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
