### ISSUE TITLE
Mejora en Chat Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#23]
Marce, se puede hacer que los mails de robotchat que llegan vayan alistando toda la conversación en cada mail?

No, no?

**Comment by mkreyness** [comment]
```
Si, se podria hacer que traiga todo lo que se fue hablando antes en
la misma conversacion, es buena idea.

El 27/11/2014 a las 21:49,
  LeandroBraier escribió:


  Marce, se puede hacer que los mails de robotchat que llegan
    vayan alistando toda la conversación en cada mail?
  No, no?
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by mkreyness** [comment]
```
Esto lo tengo medianamente resuelto, como podemos hacer una prueba
sin jorobar lo que esta en produccion ?
Fede podes armar algo paralelo que en vez de llamar a chatrio.pl
llame a chatrio2.pl ?
Y pongo que los mails te lleguen a vos Lean en vez de MS para que
veas como llegan ?

El 27/11/2014 a las 21:49,
  LeandroBraier escribió:


  Assigned #23 to
    @mkreyness.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Buenisimo Marce, cuando quieran probamos. Pasalo a leandrobraier@gmail.com al CHAT2 y probamos.

abrazo

**Comment by mkreyness** [comment]
```
ya esta cambiado el destinatario del mail, pero Fede tiene que tocar
en la web de rioancho para que haya una pagina de prueba que llame a
chatrio2.pl en vez de chatrio.pl

El 01/12/2014 a las 9:38, LeandroBraier
  escribió:


  Buenisimo Marce, cuando quieran probamos. Pasalo a leandrobraier@gmail.com
    al CHAT2 y probamos.
  abrazo
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Ok, pero entonces si alguien le escribo al chat ONLINE ACTUAL de Rio Ancho
me llega a mi?

Evitemos eso. Me referís a redireccionar el chat falso de pruebas, no el
verdadero.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-01 9:48 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
```
No, por eso dije de hacer un set de prueba separado.
Los que escriban via chatrio.pl, o sea lo que esta en produccion, le
sigue llegando a ms@rioanchocolonia.com

Lo que cambie es chatrio2.pl, un programa que por ahora esta
inaccesible. Es "de prueba", pero no sirve de mucho mientras sea
inaccesible.
Lo que hace falta es que Fede duplique la pagina del chat de
Rioancho con otro nombre, haciendo que llame a chatrio2.pl, y
entremos a probar por esa (por ahora inexistente) pagina de prueba.

El 01/12/2014 a las 9:51, LeandroBraier
  escribió:

Ok, pero entonces si alguien le escribo al chat ONLINE
  ACTUAL de Rio Ancho

  me llega a mi?


  Evitemos eso. Me referís a redireccionar el chat falso de pruebas,
  no el

  verdadero.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-12-01 9:48 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > ya esta cambiado el destinatario del mail, pero Fede tiene
  que tocar

  > en la web de rioancho para que haya una pagina de prueba que
  llame a

  > chatrio2.pl en vez de chatrio.pl

  >

  > El 01/12/2014 a las 9:38, LeandroBraier

  > escribió:

  >

  >

  > Buenisimo Marce, cuando quieran probamos. Pasalo a
  leandrobraier@gmail.com

  > al CHAT2 y probamos.

  > abrazo

  >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/23#issuecomment-65060053
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Perfecto. Entiendo Marce.

FEDE: Si estás leyendo esto, esta mejora en el chat de Rio Ancho no es
prioridad.

Necesito urgente la maquetación de Siguit. Eso es prioridad.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-01 9:55 GMT-03:00 mkreyness notifications@github.com:

**Comment by FAAREIA** [comment]
http://rioanchocolonia.com/contacto2.html

**Comment by mkreyness** [comment]
```
ahi te escribi, te llego Leandro ?

El 01/12/2014 a las 12:18, Federico
  Arena escribió:


  rioanchocolonia.com/contacto2.html
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Si, recién te respondí. Demoré unos minutos nomás.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by mkreyness** [comment]
```
En algun momento me empezo a dar que estaba "en mantenimento", o sea
que algo se rompio.
Llegaste a recibir bien threads de lo que yo escribia ?

El 01/12/2014 a las 12:26,
  LeandroBraier escribió:

Si, recién te respondí. Demoré unos minutos nomás.


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  On Mon, Dec 1, 2014 at 12:23 PM, mkreyness
  <notifications@github.com> wrote:


  >

  >

  >

  >

  >

  > ahi te escribi, te llego Leandro ?

  >

  > El 01/12/2014 a las 12:18, Federico

  > Arena escribió:

  >

  >

  >

  > rioanchocolonia.com/contacto2.html

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/23#issuecomment-65079594
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Creo que eso tiene que ver con que hay una cantidad de minutos de espera
límites que fijamos con Fede. Creo que es de 5 o 10 minutos, no recuerdo.
Consultale si es eso. Pero mañana lo seguimos a esto, no hay problema.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-01 21:55 GMT-03:00 mkreyness notifications@github.com:

> En algun momento me empezo a dar que estaba "en mantenimento", o sea
> que algo se rompio.
> Llegaste a recibir bien threads de lo que yo escribia ?
> 
> El 01/12/2014 a las 12:26,
> LeandroBraier escribió:
> 
> Si, recién te respondí. Demoré unos minutos nomás.
> 
> Leandro Braier
> 
> Producción Audiovisual & Social Media
> 
> Benteveo Producciones http://benteveo.tv
> 
> Móvil 1158717399
> 
> On Mon, Dec 1, 2014 at 12:23 PM, mkreyness

**Comment by mkreyness** [comment]
```
pero te llegó algun thread con varias respuestas en el mismo mail ?
Ese era el objetivo de toda la prueba.

El 01/12/2014 a las 23:09,
  LeandroBraier escribió:

Creo que eso tiene que ver con que hay una cantidad de
  minutos de espera

  límites que fijamos con Fede. Creo que es de 5 o 10 minutos, no
  recuerdo.

  Consultale si es eso. Pero mañana lo seguimos a esto, no hay
  problema.


  abrazo


  Leandro Braier

  Producción Audiovisual & Social Media

  Benteveo Producciones <http://benteveo.tv>

  Móvil 1158717399


  2014-12-01 21:55 GMT-03:00 mkreyness
  <notifications@github.com>:


  >

  >

  >

  >

  >

  > En algun momento me empezo a dar que estaba "en
  mantenimento", o sea

  > que algo se rompio.

  > Llegaste a recibir bien threads de lo que yo escribia ?

  >

  > El 01/12/2014 a las 12:26,

  > LeandroBraier escribió:

  >

  > Si, recién te respondí. Demoré unos minutos nomás.

  >

  >

  > Leandro Braier

  >

  > Producción Audiovisual & Social Media

  >

  > Benteveo Producciones <http://benteveo.tv>

  >

  > Móvil 1158717399

  >

  >

  > On Mon, Dec 1, 2014 at 12:23 PM, mkreyness

  > <notifications@github.com> wrote:

  >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > >

  >

  > > ahi te escribi, te llego Leandro ?

  >

  > >

  >

  > > El 01/12/2014 a las 12:18, Federico

  >

  > > Arena escribió:

  >

  > >

  >

  > >

  >

  > >

  >

  > > rioanchocolonia.com/contacto2.html

  >

  > > —

  >

  > > Reply to this email directly or view

  >

  > > it on GitHub.

  >

  > >

  >

  > > —

  >

  > > Reply to this email directly or view it on GitHub

  >

  > >

  > <

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/23#issuecomment-65079594
      > >

```
  >

  > > .

  >

  > >

  > —

  > Reply to this email directly or view

  > it on GitHub.

  >

  > —

  > Reply to this email directly or view it on GitHub

  >
```

https://github.com/LeandroBraier/WebPuroRio/issues/23#issuecomment-65166575
      > .

```
  >
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Si! me llegaron todos!

Ahora te reenvio.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-12-01 23:14 GMT-03:00 mkreyness notifications@github.com:

> pero te llegó algun thread con varias respuestas en el mismo mail ?
> Ese era el objetivo de toda la prueba.
> 
> El 01/12/2014 a las 23:09,
> LeandroBraier escribió:
> 
> Creo que eso tiene que ver con que hay una cantidad de
> minutos de espera
> 
> límites que fijamos con Fede. Creo que es de 5 o 10 minutos, no
> recuerdo.
> 
> Consultale si es eso. Pero mañana lo seguimos a esto, no hay
> problema.
> 
> abrazo
> 
> Leandro Braier
> 
> Producción Audiovisual & Social Media
> 
> Benteveo Producciones http://benteveo.tv
> 
> Móvil 1158717399
> 
> 2014-12-01 21:55 GMT-03:00 mkreyness
> notifications@github.com:
> 
> > En algun momento me empezo a dar que estaba "en
> > mantenimento", o sea
> > 
> > que algo se rompio.
> > 
> > Llegaste a recibir bien threads de lo que yo escribia ?
> > 
> > El 01/12/2014 a las 12:26,
> > 
> > LeandroBraier escribió:
> > 
> > Si, recién te respondí. Demoré unos minutos nomás.
> > 
> > Leandro Braier
> > 
> > Producción Audiovisual & Social Media
> > 
> > Benteveo Producciones http://benteveo.tv
> > 
> > Móvil 1158717399
> > 
> > On Mon, Dec 1, 2014 at 12:23 PM, mkreyness
> >

**Comment by LeandroBraier** [comment]
Marce, la firma de MS es una imagen nomás. Podemos proceder a aplicar este cambio entonces.

**Comment by mkreyness** [comment]
```
Aplicado.

El 18/12/2014 a las 10:58,
  LeandroBraier escribió:


  Marce, la firma de MS es una imagen nomás. Podemos proceder a
    aplicar este cambio entonces.
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by LeandroBraier** [comment]
Gracias MK!
