### ISSUE TITLE
Textos más breves en Versión Mobile (para el miércoles tranqui)

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#24]
Fede, me pidió MS que en la versión mobile achiquemos los textos. Esto afectaría sólo a las páginas: CARTA, FILOSOFÍA Y PROGRAMAS  de la versión mobile. Puede estar para el miércoles, sin problemas.

CARTA
Rio Ancho Gourmet Lodge abre sus puertas para honrar a sus huéspedes. 

La magia de nuestro menú de siete pasos se inspira en lo mejores frutos que brindan nuestros productores locales. 

La cocina de Rio Ancho Gourmet Lodge, es un recorrido entre los mejores productos nativos y exóticos y una experiencia única en el lugar. Tanto para comensales vegetarianos como omnívoros. 

El camino comienza con un aperitivo y nuestros panes amasados día a día. Luego la sopa crema que nos prepara para recibir el tercer paso: la entrada. 

Con el deseo de seguir descubriendo texturas; seguirá la pesca de río y la pasta casera. Con el quinto paso llegamos a una exquisita carne o vegetales.

El dulce, sugerente, y un final con infusiones o cafe, acompañados de petit fours. 

Nuestra propuesta contempla vino y bebidas. Rio Ancho cuenta con una cava especial para descubrir los vinos que Uruguay tiene para ofrecer y sorprender.

FILOSOFÍA

De un horizonte de vivencias inolvidables nace Río Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Río de la Plata y a pocos km de Colonia del Sacramento, Uruguay. La visión franca a este inmenso río es nuestro sello. 

Martin Molteni cocina

La cocina está pensada por Martin Molteni, chef reconocido mundialmente, con experiencia en hoteles de América, Europa y Oceanía, ejecutada bajo la filosofía de honrar al productor, al recolector y al trabajador de su tierra.

PROGRAMAS

Almuerzo + Distensión

Tras la recepción y el disfrute de nuestra propuesta, los comensales podrán distenderse en nuestros espacios interiores y jardines, terraza o playa según la temporada y gustos particulares.

Tardes + Té

Una selección de simples sabores a través de hebras de té, café NESPRESSO, algunos hallazgos dulces y rústicos, para deleitarse en nuestro salón comedor, de vista privilegiada. 

Atardeceres + Cocktails

A las 18 hs abrimos la barra para presentar una cocktelería de las grandes marcas de destilados. Bebidas Premium, cristalería, tragos cuidados y originales para vivir una caída del sol única en el mundo sumergidos en la inmensidad del paisaje.

Cena + Degustación

A partir de las 21hs un nuevo deleite con los más elaborados sabores de la cocina regional, preparados por nuestro Chef Gourmet Internacional en base a ingredientes e insumos propios de la estación. Además, los mejores vinos para sorprender a los más exigentes.

Lodge + Desayuno

Para quienes vienen a cenar y no desean volver al pueblo, contamos con habitaciones de confort para pasar la noche. Al día siguiente despertarán en medio de la calma y la naturaleza.

Programas de contenido

Licores caseros
Amasado de pan
Repostería
Yoga y Masajes
Avistaje de pájaros
Huerta orgánica
Equinoterapia
Cabalgatas guiadas
Arquería
Kayaking

Eventos corporativos y sociales

Realizamos todo tipo de eventos para empresas o particulares, resolviendo la gastronomía, ambientación, espacios y experiencias con una capacidad continua para 30 personas.

**Comment by FAAREIA** [comment]
Hola Lea, ahi subí una nueva actualización. Éste issue ya estaría:

http://www.rioanchocolonia.com/__nuevo/

**Comment by LeandroBraier** [comment]
Quedó impecable, Fede. Ya lo paso para aprobación así los subimos. abrazo

**Comment by LeandroBraier** [comment]
Fede, van pequeñas modificaciones para la versión mobile:

FILOSOFIA/RIO ANCHO

Quitar la raya debajo del título: Rio Ancho. En algunas versiones cae sobre los textos.

CARTA

Algunos textos están muy pegados a las fotos y otros no. Quedan mejor separados, como el caso del tercer y quinto texto. Los otros tres deberían quedar como esos, con el mismo espacio arriba y abajo del texto.

LODGE

La parte verde agua del final tapa donde dice brochure/descargar. Dale dos líneas de espacio abajo por las dudas y listo.

CHAT

Mientras estabas de vacaciones, con MK sacamos el chat a pedido de MS. Porfa, cuando subas esta nueva versión, con faceta mobile y faceta web, que no quede online de vuelta el chat. 

VERSIÓN MOBILE EN INGLÉS

Ya tenés los textos traducidos en RIO ANCHO MAQUETADOR.

abrazo

**Comment by FAAREIA** [comment]
Todo listooooooooooooo

**Comment by LeandroBraier** [comment]
No lo veo che, lo hiciste en la misma url?

FILOSOFIA/RIO ANCHO

Sigue la línea ahí.

CARTA

Sigue igual

CHAT

Se fue en la versión mobile. Lo veo ok. Pero tenés que sacarlo en la versión web también. El chat no va más.

LODGE

La parte verde agua del final tapa donde dice brochure/descargar. Se ve un poco más que antes pero sigue tapando. Dale un poco más de espacio y probalo en tu móvil porfa.

VERSIÓN MOBILE EN INGLÉS

Donde accedo a la versión en inglés?

**Comment by FAAREIA** [comment]
Que raro Lea, debes tener el sitio entero cacheado.
Lo de la banderás tenes razón! no estan en mobile, ahi las agrego

**Comment by FAAREIA** [comment]
Ahi esta todo listo Lea!
Dale F5 nomás

**Comment by LeandroBraier** [comment]
Nop, recién borré el caché entero del navegador mio y lo sigo viendo igual. 

Te adjunto dos capturas de ejemplo.
![screenshot_2015-01-09-15-29-30](https://cloud.githubusercontent.com/assets/6719872/5686199/c51611a2-981f-11e4-8fdc-c5a7c7e7cd66.png)
![screenshot_2015-01-09-15-29-03](https://cloud.githubusercontent.com/assets/6719872/5686200/c5161b7a-981f-11e4-9c21-c48a93bd7351.png)

**Comment by LeandroBraier** [comment]
Lo sigo viendo igual, Fede. Como las capturas que te pasé recién.

¿Seguro lo estás actualizado en este link?

http://www.rioanchocolonia.com/__nuevo/

Porque sigo viendo todo igual, incluido el chat en la versión web.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No claro, como son cosas muy puntuales las estoy poniendo en producción directamente ^^

**Comment by LeandroBraier** [comment]
Ahhhhh!!! Ok. Ahora lo veo.

Está todo corregido pero veo nuevos problemas en la VERSIÓN MOBILE.

FILOSOFÍA

Bajar el link al photobook al pie de la página, porque queda todo encimado
como ves en la captura. El teléfono y links a Facebook y Twitter borralos
del header, porque ya están al pie también. Así te queda más espacio para
las dos banderitas.

MULTILENGUAJE

Los botones de banderitas son muy chicos para mobile, hacelos más grandes.

CARTA

Los espacios están bien corregidos pero fijate que al pie del cuarto texto
("Con el deseo...") sobre espacio. Borrale una línea nada más. Fijate que
en la versión en inglés quedó perfecto.

PROGRAMS

Sigue diciendo PROGRAMAS DE CONTENIDO. Debe decir "Content programs".
Después dice "Las temáticas disponibles son" y debe decir "Options
available are:

Y la lista de opciones se ve mal, con espacios entre distintas opciones de
cada columna.

RESERVATIONS (versión en inglés)

Te siguen quedando "Programas de contenido" y "Eventos corporativos y
sociales" en español. Eso tampoco lo corregiste en la versión web en
inglés. Yo te mandé la traducción para eso.

El mapa es muy grande para Mobile. Impide scrollear para arriba cuando te
vas abajo de todo.

El formulario no funciona ni en mobile ni en la web o al menos no aparece
ningún mensaje que avise que el mensaje se envió. Solo el botón de SEND
queda en blanco.

CONTACTO / CONTACT

Este formulario tampoco funciona ni en mobile ni en la web o al menos no
aparece ningún mensaje que avise que el mensaje se envió. Solo el botón
de SEND queda en blanco.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, ahi estuve corrigiendo todo.
Lo de Filosofía no se bien a que te referis. En versión mobile, osea menor a 768px de ancho, aparece solo el boton del menú desplegable y 2 banderas que les agrandé el area del click. Fijate bien porque no aparece ni el tel, ni el fb, ni nada. (La captura no la vi adjunta)

Todo lo otro ya esta corregido, incluyendo lo de los formularios que fue un dolor de cabeza.

Cualquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Che, los formularios me siguen funcionando igual. No me aparece ningún mensaje en Mobile, solo se pone el botón SEND en blanco. En la versión web sale bien. Consultale a MK porque es grave si esto no está funcionando. Urgente por favor.

Respecto de los botones de idioma ahora me aparecen más despejados pero todavía son muy pequeños para mobile. FIjate si les podés dar un poco más de tamaño. Son apenas clickeables.

Los otros cambios los veo OK .

abrazo

**Comment by FAAREIA** [comment]
Oka, le optimizo eso de las banderas.
Marce, el tema de los formularios de las páginas en ingles no andan porque la ruta de "include_once" del .php de contacto o reservas lleva a la nada. Ayer traté de ponerle una ruta relativa o absoluta, válida y lógica como cualquiera que pongo en el HTML, pero no me funcionó nada. Es por eso que termine duplicando los 2 php y la carpeta del include "inc".
Ahora el tema es que en versión desktop va bien pero en mobile no funciona nada, ¿tampoco en castellano lea?
Imagino que el problema es el include y no otro que desconozco

**Comment by LeandroBraier** [comment]
Si, lo rechequeé ahora. En castellano pasa lo mismo.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 8:14 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Listo lo de las banderas ^^

**Comment by LeandroBraier** [comment]
Buenisimo. Puede ser que la bandera de españa se vea más chica que la de
Inglaterra?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si, es menos ancha. =/

**Comment by FAAREIA** [comment]
En chico safa, pero más grande achicarla como la de españa se deforma. Y la de españa más grande también se deforma si la igualo a la inglesa

**Comment by LeandroBraier** [comment]
jaja ¿pero no hay otra versión disponible de la bandera de españa que sí se
pueda expandir? No queda bien así.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 10:06 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahora voy a tratar de conseguir otra bandera de inglaterra, aunque te digo que esas dos me costaron de conseguir, hay muchas versiones oficiales de banderas

**Comment by LeandroBraier** [comment]
Es que el tamaño de la de Inglaterra está bien, la de España es muy
chiquita. Estirala y listo, no pasa nada. Es muy simple, son 3 colores. Es
solo para la versión mobile.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-13 11:07 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahora si, para mobile quedaron iguales =D

**Comment by LeandroBraier** [comment]
Excelente Fede!!! La verdad que quedó muy fina la web. Yo la mostraría como ejemplo de portfolio, está muy buena en ambas versiones.

Seguramente te moleste más adelante cuando tenga la traducción al alemán y al francés jeje pero falta me parece. abrazo

**Comment by FAAREIA** [comment]
Gracias Lea!
Aleman? O_O ...cuando sea el momento le damos

Abrazo
