### ISSUE TITLE
Firmas Rio Ancho en HTML

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#25]
Fede, necesito que me armes en versión HTML las firmas de mail de Rio Ancho que te subí al Dropbox de RIO ANCHO MAQUETADOR/FIRMAS. Son para incluir como firmas de mails para Marce y todo el equipo de Rio Ancho.

Sería ideal que lo dejes listo junto con los demás pendientes esta semana antes de irte. Avisame si no llegás por favor.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, el tema con las firmas de email es que se ponen desde la configuración de cada email. Es como el ckeditor, por lo que no se puede maquetar en realidad, sino simplemente estilizar.
Para este caso, que hay 2 columnas y encima se usa una tipografía no-safe (arial, georgia, times new roman) lo mejor es una simple imagen y listo.

La idea es que pongan lo siguiente, como imagen en la firma.

http://www.rioanchocolonia.com/firmas/arturo-abadia.png
http://www.rioanchocolonia.com/firmas/deborah-bertolesi.png
http://www.rioanchocolonia.com/firmas/marcelo-susevich.png
http://www.rioanchocolonia.com/firmas/miri-fioramonti.png

**Comment by LeandroBraier** [comment]
Entiendo, Fede. Calculo que con esto nos arreglamos. Te aviso. gracias!
