### ISSUE TITLE
Firmas Río Ancho en HTML

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#26]
Fede, te subí a la carpeta FIRMAS de RIO ANCHO MAQUETADOR un Illustrator con todas las firmas. Lo que necesito es que, más allá de las que hiciste en imágenes, me hagas unas en Html, con Google Fonts para evitar diferencias de fuentes y tamaños. Me lo pidió específicamente Marce Susevich para que los mails, la web que aparecen en el diseño sean clickeables.

abrazo

**Comment by FAAREIA** [comment]
No puede haber google fonts. Es lo mismo que un mailing, pero algo más tosco.
Si quieren lo hago en HTML con esos links, pero no va a tener fuentes google.

**Comment by LeandroBraier** [comment]
Ok, hacelo en html con los links y vemos cómo funciona.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-06 11:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi te mandé una prueba desde un mail que me cree en rioancho.
Si esta ok preparo las demás y se las pasamos con un tutorial para hacerlo.
Sino me van a tener que pasar las claves

**Comment by LeandroBraier** [comment]
Dale, me parece bien eso. Te respondí la duda tuya. avancemos

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-08 15:43 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Después avisame como les fue con el mini tutorial, la idea es que peguen el código que les mandé

**Comment by LeandroBraier** [comment]
Dale, yo lo pruebo y te aviso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Che, lo probé y el mail y la url de la web no me quedan clickeables. Puede
haber algún error en el código?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-08 17:53 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Hola Fede! Viste esto?

**Comment by FAAREIA** [comment]
Si, no recuerdo si te habías contestado o no. Parece que no =)
Medio raro que no respete la url del email y la web. Lo que probé yo era mandando un email desde el webmail online......ahi funcionó. Debería de funcionar si lo metes en un outlook o similar.
Capas que tenes algo que deshabilita los links también, fijate eso

**Comment by LeandroBraier** [comment]
Recién probé el envío. Es cierto, al enviar el mail sale perfecta la firma.
Lo único que tiene es que no se pone azul y subrayado como cualquier link.
Haceme una versión subrayada para todos los html y estamos listos.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-09 14:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Te mandé un mail hace un rato, avisa si lo ves OK asi

Abrazo

**Comment by LeandroBraier** [comment]
Perfecto. Te aviso cualquier cambio. abrazo
