### ISSUE TITLE
Correcion en Seccion Lodge

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#27]
En la Habitación Master Suite la línea:

"El acceso a esta habitación requiere transitar piso por escalera."

VERSIÓN EN INGLÉS

"Access to this room requires the use of stairs."

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias!

**Comment by LeandroBraier** [comment]
Pequeña corrección en la versión en español: "El acceso a esta habitación requiere el uso de escalera."

La versión en inglés está ok.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
