### ISSUE TITLE
Feed de Trip Advisor

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#28]
Fede, cómo va?

Tenemos que subir el feed de trip advisor de RIo Ancho a la web. Donde te parece que iría mejor?

Para mi tendría que ir en la landing, RIO ANCHO, debajo del mensaje filosófico, no? Qué decís?

abrazo

**Comment by FAAREIA** [comment]
Cómo es el feed de trip advisor?
Es una página de resumen, informativa del sitio?

**Comment by LeandroBraier** [comment]
Entiendo que sería específicamente este el feed:

http://www.tripadvisor.com/Widgets-g298066-d7350434-c6-a_widgetKey.selfserveprop-Rio_Ancho_Gourmet_Lodge-Colonia_del_Sacramento_Colonia_Department.html

**Comment by FAAREIA** [comment]
Ahi lo vi, me parece medio grande. ¿Dónde habría que ponerlo?
Sino se puede optar por una solución menos invasiva al diseño del sitio, que muestre el logo de trip advisor y que sirva como link a la página de rio ancho en trip advisor.
¿Qué decis?

**Comment by LeandroBraier** [comment]
Es que el pedido fue que se vieran las reviews. Quizá se puede customizar
en un tamaño un poco más chico no?

Yo lo metería en filosofía a la derecha del texto. Abajo en la versión
mobile. qué decís?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-27 13:03 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Si, se puede quitar alto si sacamos el "TripAdvisor Traveler Rating" y/o "TripAdvisor Ranking".
Se puede meter en esa sección. En versión mobile estaria en el mismo lugar pero reubicado, no estaría en otro bloque de contenido, sino tendría que duplicar el código.

**Comment by LeandroBraier** [comment]
Claro. Intentemos una versión sin recortarlo entonces porfa y vemos como
queda. Después si no queda bien sacamos eso.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-01-27 14:02 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/index2.html
Dale F5. En resoluciones menores a 640px, el bloque de trip advisor lo oculté.

Si esta ok, lo replico en ingles y lo subo.
Abrazo

**Comment by LeandroBraier** [comment]
La veo OK, pero no me termina de convencer al final que sea en esa página.

Hagamos así, este index alternativo dejalo y hacé un home2 donde aparezca
también abajo a la derecha. El home 2 me refiero a la página de Inicio. Con
esas dos versiones les muestro a ellos a ver donde prefieren que aparezca.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hola Lea, ahi lo probe pero no entra. El tema es que el alto compromete mucho al bloque. El que tenga un monitor como el mio o más chico, no lo va a ver completo. Más allá de eso, tampoco veo que quede bien, se genera una forma rara entra la banda horizontal y este bloque vertical a un costado.

![sin-titulo-3](https://cloud.githubusercontent.com/assets/6184969/5958429/16655616-a7a3-11e4-85d7-857142b1dc5d.jpg)

**Comment by LeandroBraier** [comment]
Entiendo. Perfecto. Entonces mando esta primera versión para aprobación y
te aviso cuando la podes subir.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, está ok la versión. Lo único que piden es si se puede poner un poco más de separación entre las dos flechitas de back y forward del slideshow y el feed, para que no queden tan pegados. Si podés eso pasame.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo ajusté Lea, ya esta subido en español e ingles.

Abrazo

**Comment by LeandroBraier** [comment]
Genial, Fede. Gracias!
