### ISSUE TITLE
Modificaciones pequeñas Página Lodge

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#29]
Fede, hay unas pavadas que necesito cambiar en esta sección

Al pie donde dice "Ver Brochure" te muestra el Photobook. Necesito que muestre el Brochure pero que, a su vez, a ese brochure le cambies el nombre por "Factshett". Es decir, debe decir Ver Factsheet / Descargar 

Sobre el slideshow, al igual que como ocurre actualmente en la sección FILOSOFIA debería haber un texto que explique la sección y, debajo del texto, una flecha que invite a leer hacia abajo.

El texto sería:

"Mientras la naturaleza invita a dar un paseo para reconectarse con el río y el bosque, el admirable espacio de confort y relax espera paciente a cada agasajado. Tres habitaciones perfectamente equipadas para descansar en la mayor comodidad y desconectarse de las obligaciones. También disponible el servicio "3 Bedroom Suite", para reservar las tres habitaciones juntas de modo exclusivo."

**Comment by FAAREIA** [comment]
Hola Lean, cuando puedas pasame la traducción del texto

**Comment by FAAREIA** [comment]
Ahi esta actualizado Lodge y Accomodations, pero falta el texto en la versión ingles.

Abrazo

**Comment by LeandroBraier** [comment]
Aquí va el texto en inglés Fede.

"While nature invites for a walk to reconnect with the river and the forest, a delightful shelter of comfort and relaxation waits patiently to each honoree. Three rooms to relax in comfort and keep obligations apart. Also available "3 Bedroom Suite" service, to book exclusively the three rooms together."

La flechita que pusiste necesitaría que esté debajo del párrafo, para que se entienda que hay más cosas abajo. Además de esto, te envío por mail el factsheet (antiguo brochure) corregido, para que cambies el archivo actual por ese.

abrazo

**Comment by FAAREIA** [comment]
Ahi le agregué el texto en ingles.
Lo de la flecha no entendi, las flechas que hay son para avanzar o retroceder las fotos. No metería más flechas y si la metemos hay que meterlas en todas las secciones que habran con foto fullscreen

**Comment by LeandroBraier** [comment]
Me refiero a que necesito algo que indique que hay más información debajo del slideshow con el texto. La gente no entiende que debajo está la info de las habitaciones y se queda boyando.

**Comment by FAAREIA** [comment]
Ahi puse la flecha Lea en los 2 idiomas.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo
