### ISSUE TITLE
Agregado Mínimo Sección Filosofia

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#30]
Fede, en el párrafo principal de esta sección, luego de la frase final "puede contemplarse desde todos los espacios de la casa" cambialo por "puede contemplarse desde todos los espacios de una casa atendida por sus dueños."

amen

**Comment by FAAREIA** [comment]
Hola Lea, ya esta lo de la frase. Fijense si quedó bien la versión ingles, acordate de pensar siempre x2 para este sitio.

Abrazo

**Comment by LeandroBraier** [comment]
Está perfecto Fede! Gracias!
