### ISSUE TITLE
Tarifario Web. DEADLINE: 4/3

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#31]
Fede, necesitamos subir las tarifas al sitio web. En principio en la versión en español. Cuando esté resuelto el tema ahí lo traducimos.

La referencia de cómo mostrarlo es esta:

http://awasiatacama.com/en/info/rates

Te envío el doc con la info por mail. Lo que iría "tipo chart" como el de Awasi es la esta listita de precios.

ALOJAMIENTO 
Hab Deluxe base DBL   500
Junior Suite  base DBL   600
Master Suite  base DBL   750
3 bedrooms suite…  1600
Pax adicional (DLX y JrSuite MAX 1, Master Suite MAX 2)                190
Whole house: los 3 cuartos. Hasta 8 pax con pensión completa.          2500  
Todos los ambientes en exclusiva 
Day Use   100
Experiencia Menu Degustación 7 Pasos                                  100
- Los precios expresados en USD.

Después, tal cual Awasi, el resto aparece como texto a scrollear, desde Servicio All Inclusive en adelante.

abrazo

**Comment by FAAREIA** [comment]
Lo ponemos en lodge la tabla? arriba de las habitaciones o abajo?

**Comment by LeandroBraier** [comment]
Yo había pensado en una sección propia o, en caso de no poderse incluir en
el menú, que tenga un botón aparte como en Awasi que sea clickeable en
todas las páginas. No sé si me explico bien.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Oka, en el menú lo ponemos entonces.

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/tarifario.html

Ahi va el tarifario Lea. Habría que estilizarlo bastante más. Dejar el texto tirado como awasi no funciona en este caso porque hay mucha información para mostrar y de distinto tipo.

**Comment by LeandroBraier** [comment]
Ok, genial. Avancemos a estilizarlo como les parezca mejor en la linea de la estetica del sitio.

Abrazo

**Comment by FAAREIA** [comment]
Fijate ahora Lea: http://www.rioanchocolonia.com/tarifario.html
Sigue siendo mucha data igual para mi

**Comment by LeandroBraier** [comment]
Por ahora lo veo perfecto, Fede. Lo mando a ver y vemos qué dicen. Solo te pediría que dentro del menú pusieras "tarifas" bien a la derecha, a la izquierda de "Contacto"

abrazo

**Comment by FAAREIA** [comment]
Ahi lo acomodé lea

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, te paso un par de correcciones muy simples. Aplicalas y ya tenés el OK para subirlo. Puede ser hoy a la tarde, prioridad de hoy es Klaukol.
1. Quitarle la negrita al 100 de la "Experiencia Menu degustación" 
2. Donde dice "Pax adicional" reemplazar por "Huesped adicional"
3. Sumar al chart 1 línea más que diga: Lodge Full Board $1600.

abrazo

**Comment by LeandroBraier** [comment]
Te subí a Río Ancho Maquetador el tarifario traducido, para que lo subas también a la versión en inglés.

Avisame cuando esté arriba porfa. En español tendría que ser hoy.

abrazo

**Comment by FAAREIA** [comment]
Ahi actualicé el html en español
Ahora hago el html en ingles

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/tarifario.html
http://www.rioanchocolonia.com/en/price-list.html

En ingles falta traducir:
**Incluye Bebidas sin alcohol, Cocktail de la casa y Vino de la casa**

**Comment by LeandroBraier** [comment]
Va la traducción!

  Non alcoholic drinks, cocktails & house wine included.

Ya corregilo y subilo online cuanto antes, que se vea el tarifario en el
menú porfa.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi lo actualicé y lo subi, estoy corrigiendo algo que quedo mal en el tarifario en ingles. No se porque no scrollea el browser -_-

**Comment by FAAREIA** [comment]
Ahi está

**Comment by LeandroBraier** [comment]
Gracias Fede, pero está mal el link en el menú.

Pusiste tarifas.html y es tarifario.html

Corregilo porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi lo solucioné, gracias por avisar.

**Comment by LeandroBraier** [comment]
Perfecto. Ahora sí
