### ISSUE TITLE
Pequeñas modificaciones en Sección Programas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#32]
Fede, necesito modificar el texto de la sección "Lodge + Desayuno"

Donde dice "...contamos con habitaciones de confort para pasar la noche" debe decir "...contamos con 3 exclusivas habitaciones de máximo confort para pasar la noche"

No hay apuro.

abrazo

**Comment by FAAREIA** [comment]
Ahi ya esta actualizado lea

Abrzo

**Comment by LeandroBraier** [comment]
Gracias Fede!
