### ISSUE TITLE
Cambio de palabra en Reservas y Programas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#33]
Fede, necesito cambiar el programa llamado "Lodge + Desayuno" por "Lodge Full Board" (tanto en la versión en inglés como en español.

Esto está tanto en la sección Programas como en Reservas.

abrazo

**Comment by FAAREIA** [comment]
Actualizado en los 2 idiomas

**Comment by LeandroBraier** [comment]
Gracias Fede!
