### ISSUE TITLE
Pequeño cambio de texto en Lodge 

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#34]
Tanto en castellano como en inglés, agregar la palabra "exclusivo"

Donde dice "Tres habitaciones perfectamente..." poner "Tres exclusivas habitaciones..."

Donde dice "Three rooms to relax" poner "Three exclusive rooms to relax"

Solo eso.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo
