### ISSUE TITLE
Subir Factsheet Digital Traducido a Versión en inglés

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#35]
Fede, te subí a la carpeta de Dropbox RIO ANCHO MAQUETADOR un pdf con el Factsheet traducido al inglés para subir a la versión en inglés.

Avisame cuando esté porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi subi eso y corregí también el bloque del trip advisor del sitio en ingles. El bloque estaba en castellano, lo pasé al ingles.

Abrazo

**Comment by LeandroBraier** [comment]
Genial Fede! Eso te iba a pedir y me olvidé. 

Gracias.

**Comment by LeandroBraier** [comment]
Che, sigo viendo el mismo factsheet en español yo.

**Comment by FAAREIA** [comment]
Solucionado!

**Comment by LeandroBraier** [comment]
Genial. Ahora sí, Fede.

Una cosita más. La banderita inglesa al final quedó del mismo ancho pero menor altura que la española. Se podrá estirar un poquito? Total a ese tamaño ni se nota. Es para que se vea mejor y para que queden del mismo tamaño las dos.

**Comment by FAAREIA** [comment]
Hola Lea, estan al mismo tamaño. Capas lo que te engaña un poco es que la opacidad del idioma no activo o que en los bordes tiene blanco.

**Comment by LeandroBraier** [comment]
Ah, ahí está la cuestión. Quitemosle el borde blanco a la que tenga o
pongamoselo a las dos de última, pero que queden iguales.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-03-19 8:13 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
El border blanco es porque la bandera inglesa es asi. En las esquinas esta en blanco pero por la bandera, no porque le haya puesto un borde yo. Si queres la agrando un poco, pero se va a notar.

**Comment by LeandroBraier** [comment]
Ya está, dejemoslo así.

Qué fundamentalismo banderil.

abrazo
