### ISSUE TITLE
Problemas de usabilidad móvil en el sitio de Río Ancho Colonia

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#37]
Sin apuro, Fede. 

Te paso un informe que nos mandó al mail de analitics Google. Parece que se puede optimizar mucho más la web de Rio Ancho para navegación en móviles.

Herramientas para webmasters
 Corregir los problemas de usabilidad en móviles de http://www.rioanchocolonia.com/

Para: webmaster de http://www.rioanchocolonia.com/

Los sistemas de Google han probado 30 páginas de tu sitio y han detectado que un 50% de estas contiene errores graves de usabilidad en móviles. Los errores de estas 15 páginas afectan gravemente a la experiencia que tienen los usuarios de móviles en el sitio web. En la Búsqueda de Google, estas páginas no se considerarán optimizadas para móviles y, por lo tanto, se mostrarán y clasificarán de forma adecuada para los usuarios de smartphones.

Corrígelo ahora:

1  
Busca las páginas problemáticas
Consulta un informe de las páginas no optimizadas para móviles que se han detectado en tu sitio y de los problemas que se han encontrado.

Error de usabilidad Páginas con errores
Elementos táctiles demasiado próximos entre sí 15
Tamaño de fuente pequeño 15
Ventana gráfica no configurada 15
Uso de Flash 1

2  
Obtén información acerca del diseño optimizado para móviles
Puedes utilizar varias técnicas para optimizar el sitio para móviles. En concreto, busca la información sobre los problemas que se aborda en Herramientas para webmasters.
Seguir las instrucciones
3   Corrige los problemas de usabilidad en móviles de tu sitio
Soluciona los problemas que impiden que el sitio esté optimizado para móviles.
¿No sabes cómo hacerlo?

• Si el sitio está diseñado con un software, como Wordpress o Joomla (también conocido como "Sistema de gestión de contenido" o CMS), lee los pasos sencillos para optimizar un CMS para móviles.

https://developers.google.com/webmasters/mobile-sites/website-software/

• Lee más información sobre cómo diseñar sitios web optimizados para móviles en el sitio para desarrolladores.

• Publica más preguntas en el Foro central para webmasters . Indica el tipo de mensaje [WNC-451500].

**Comment by LeandroBraier** [comment]
Fede, cuando puedas revisá esto. Aunque sea para fines de la semana que viene.

abrazo

**Comment by FAAREIA** [comment]
Hola Lea, voy a tratar de verlo pero no creo llegar. Además de todo lo actual, tengo qe chequear todo el sitio de Uruguay y Paraguay y hacer responsivo lo que falta de Parex.

**Comment by LeandroBraier** [comment]
Ok. Esto no es prioridad.

**Comment by braulio-evangelisti** [comment]
Lea, en el informe de analitics estan discriminadas cuales son las 15 paginas que presentan errores de usabilidad?

Pregunto esto porque por ejemplo el error que marca "Ventana gráfica no configurada" esta configurado en todo archivo visible del sitio, hay algunos que no lo tienen configurado, pero son archivos que no lo necesitan porque no se ven, son archivos de plugins como el captcha o los iconos.
Si hubiera una lista podria revisar especificamente cada archivo y ver si es real el error o solamente lo esta marcando porque revisa cada archivo que este en el sitio, aunque no sea publico.

**Comment by LeandroBraier** [comment]
La verdad que desconozco Braulio. Igual si podemos ajustar eso en todas las páginas aunque no se vea mejor, porque Google premia eso con posicionamiento. Esta es toda la info que me dio de feedback Google.

**Comment by braulio-evangelisti** [comment]
Segun dice Google te lista en el informe o en el panel cuales archivos son, seria de mucha utilidad saberlo. Si es posible necesitaria los datos de la cuenta de analitics para poder corroborarlo.

**Comment by LeandroBraier** [comment]
Dale, te la paso. Quizá soy medio queso para verlo.

Usuario: benteveoanalytics
Clave: la misma de deposit

El mail es este:

https://mail.google.com/mail/u/0/?pli=1#inbox/14c31b74fd29fe28

**Comment by braulio-evangelisti** [comment]
Listo Lea, todos los errores que marcaba eran en archivos dentro del directorio /__nuevo/ que estaba en el raiz del sitio, con Fede ya lo sacamos por ende estan corregidos y google no los va a volver a encontrar.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente, Braulio. Gracias!
