### ISSUE TITLE
Cambio de Widget Trip Advisor

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#38]
Fede, tranquilo, con tiempo, cuando puedas cambiá el widget de Trip Advisor de Río Ancho por este que te paso acá, que muestra reviews y calificaciones pero no el puesto en el ranking de hoteles, que a Marce no le gusta.

<div id="TA_selfserveprop211" class="TA_selfserveprop">
<ul id="FdVtSmz0z" class="TA_links ykRrpy">
<li id="eOAZ5cJVX" class="VRzbyVD9">
<a target="_blank" href="http://www.tripadvisor.com/"><img src="http://www.tripadvisor.com/img/cdsi/img2/branding/150_logo-11900-2.png" alt="TripAdvisor"/></a>
</li>
</ul>
</div>

<script src="http://www.jscache.com/wejs?wtype=selfserveprop&amp;uniq=211&amp;locationId=7350434&amp;lang=en_US&amp;rating=true&amp;nreviews=5&amp;writereviewlink=true&amp;popIdx=false&amp;iswide=false&amp;border=true&amp;display_version=2"></script>

**Comment by LeandroBraier** [comment]
Te lo mando por mail

abrazo

**Comment by FAAREIA** [comment]
Ok perfecto, si es solo no mostrar el ranking de los hoteles, ya se lo oculté por CSS en ambos idiomas.
Dale F5 y fijate. Cualquier cosa decime
Abrazo

**Comment by LeandroBraier** [comment]
Está perfecto así. Gracias!

**Comment by LeandroBraier** [comment]
Fede, ahora Rio Ancho es nº 1 en su categoría, así que quieren volver al embed que teníamos antes, el que muestra el puesto nº 1. Pasaselo a Braulio si no lo podés subir mañana.

**Comment by LeandroBraier** [comment]
Necesitamos también un widget de TripAdvisor que aparezca en la versión mobile, para que al clickear muestre las fotos que están en TripAdvisor. Busquen el widget adecuado. Puede ser el más chiquito, no hay problema. Lo importante es que clickeando lleve a las fotos.

abrazo

**Comment by FAAREIA** [comment]
No puede esperar 1 día más este issue?

**Comment by LeandroBraier** [comment]
Si, puede esperar 1 día más.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-06-03 9:17 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Braulio, porfa hoy sin falta actualicemos esto. Es una pavada, volver al widget anterior que mostraba el puesto en el ranking del hotel en TripAdvisor. Ahora estamos nº 1 y por eso queremos que se vea.

abrazo

**Comment by braulio-evangelisti** [comment]
Listo Lea. Chequealo nomas.

Abrazo

**Comment by LeandroBraier** [comment]
Excelente. Gracias!

**Comment by LeandroBraier** [comment]
@braulio-evangelisti 

Braulio: un pedido simple para mañana. Rio Ancho dejó otra vez de ser nº1 en Trip Advisor, así que habría que quitar el widget último y volver a la versión anterior. Para mañana está bien.

abrazo

**Comment by braulio-evangelisti** [comment]
Ya esta Lea.
Le arme un pequeño js que oculta el bloque del puesto si no es N° 1 asi no hay que andar ocultandolo si cambia.

Abrazo

**Comment by LeandroBraier** [comment]
jajaj Excelente solución!

Gracias Braulio.

abrazo

**Comment by LeandroBraier** [comment]
Brau: Rio Ancho volvió a estar primero pero no apareció el puesto automáticamente. No debería?

Porfa apenas puedas cambialo.

**Comment by LeandroBraier** [comment]
@braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
Ahi esta lea, el script estaba andando bien, me habia olvidado de borrarle el css que lo ocultaba "a mano"

Abrazo

**Comment by LeandroBraier** [comment]
Muchas gracias Brau!!

Ahora prioridad newsletter de Agosto de Klaukol porfa. Necesitamos tenerlo para dentro de dos horas máximo. Llegás?
