### ISSUE TITLE
Cambio de palabra en Tarifario y Price List en la Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#39]
Fede, hoy durante el día, sin tanto apuro, necesito cambiar las siguientes palabras.

En TARIFAS:

donde dice "Whole house: los 3 cuartos" debe decir "Casa completa"

donde dice "Lodge Full Board" debe decir "Suite de 3 habitaciones" y en la columna CLASE agregale "hasta 6 pax con pensión completa"

En la versión en inglés, en PRICE LIST:

donde dice "Lodge Full Board" debe decir "Suite of 3 bedrooms" y en la columna CLASS agregale "Maximum 6 guests with full accomodations"

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Perfecto.

Solo quitá la frase "los 3 cuartos" de "Casa completa". Que quede solo "Casa completa" en esa celda.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
