### ISSUE TITLE
Optimización Imagenes Río Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#4]
Fede, estoy notando que está pesada la web para cargar. Busquemos la forma de optimizar los JPG para que no tarden tanto en cargar, puede ser comprimiendo o puede ser mediante un orden de loading distinto, no sé.

A esto te sumo:

2) El logo esta en png, pero no esta preparado para retina. Tenemos que
prepararlo para retina, svg no puede ir porque Gourmet Lounge se va a
renderizar y nosotros necesitamos que sean pixeles.

3) Sumar la foto de Martin Molteni en la sección Río Ancho que te envío por mail.

abrazo

**Comment by FAAREIA** [comment]
El tema es que las fotos son wallpapers y de 1920 x 1100.
La altura va variando pero es 1000, 1100, 1200.

Siendo un sitio tan visual, habria que ver si bajarle la calidad o mantenerla.
- Lo de retina lo veo
- Lo del chef ya esta

**Comment by LeandroBraier** [comment]
Fijemonos cómo podemos hacer. Optimizarlas lo más posible. Quizá la
solución sea poner un filtro para conexiones lentas y a esas mostrarles
fotos de menor calidad. Creo que se puede hacer eso no?

Respecto del chef lo veo OK lo de las columnas. Ahora cambiá la foto por la
que te envié por mail hace un ratito con la cara del Chef mismo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Le bajé un poco los tamaños a todas las imagenes del sitio, pero cada una pesa entre 250 y 440 KB, son imágenes muy grandes. Habrá secciones más livianas que otras, igualmente hay un loading.
Como ya lo vimos en otro sitio, detectar la conección el usuario consume conección y ponerle una imagen en baja calidad podría resultar en una mala experiencia, si es que esta en desktop.

Lo de retina ya esta listo, dale F5 asi lo ves.

**Comment by LeandroBraier** [comment]
Perfecto todo. Por ahora me carga bien. Supongo que en conexiones más lentas andará más lento pero no queremos gente con conexión lenta en Rïo Ancho jeje

Por ahora estamos OK con esto. Cierro el ticket. Gracias Fede!

**Comment by FAAREIA** [comment]
Joya, si vemos que tiene muchas conexión desde celulares, lo analizamos. Igualmente retocar el sitio para lograrlo puede implicar rehacer mucha funcionalidad, pensá que esto vino hecho, no es custom.
Por otra parte, si comparamos, el video de Benteveo TV, solamente el video, ocupa más que algunas secciones del sitio.
