### ISSUE TITLE
Pequeña corrección en Sección Reservas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#40]
En Reservas:

En el menú, donde dice "Lodge Full Board" debe decir Casa Completa (en la versión en español) y Whole house (en la versión en inglés). Además se debe agregar Suite 3 hab (en la versión en español) y  Suite 3 bed ((en la versión en inglés).

Solo eso.

abrazo

**Comment by LeandroBraier** [comment]
Fede, necesitaría hoy a la noche a más tardar tener impactada esta modificación porfa.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
