### ISSUE TITLE
Agregado de Pop Up a Web Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#41]
Al ingresar, debe aparecer un pop up estático con la imagen que te adjunto.La imagen debe ser clickeable y llevar a descargarse el otro flyer, que te adjunto debajo.

Cuando lo tengas listo no lo pongas en front directamente, ponelo en versión interna para que se lo pueda mostrar a Marce y equipo y que lo aprueben.

![pop-up-rio-ancho-gourmet-day](https://cloud.githubusercontent.com/assets/6719872/7170820/b74ae5ec-e3a7-11e4-8cc8-37a0615c497c.png)

![original-flyer-a4-rio-ancho-2](https://cloud.githubusercontent.com/assets/6719872/7170825/cd2a1d10-e3a7-11e4-8c8c-344b7fa1414f.png)

**Comment by braulio-evangelisti** [comment]
http://www.rioanchocolonia.com/_index2.html
