### ISSUE TITLE
Pequeño agregado de teléfonos a la sección de contacto

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#42]
Fede, necesito agregar hoy durante el día los siguientes teléfonos a la sección de contacto:

54 11 5254 4381 BUENOS AIRES
34 91 198 1933 MADRID SPAIN 
44 203 318 3875 LONDON UNITED KINGDOM 
1 415 766 9806 SAN FRANCISCO: CENTRAL DA UNITED STATES

Van agregados debajo del teléfono que figura actualmente, que es en Uruguay.

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!
