### ISSUE TITLE
URGENTE corrección en Tarifario Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#43]
Quitar la parte de "Comisión 10 % Minoristas 20 % Mayoristas" tanto de la parte en castellano como en inglés. URGENTE PORFAVOR

**Comment by FAAREIA** [comment]
hecho

**Comment by LeandroBraier** [comment]
Va un pequeño cambio más en Tarifario que puede ser para mañana nomás:

La leyenda "todos los ambientes en exclusiva" se refiere solo al item "Casa completa". Debería ir en la misma "celda" de esa tabla y no abajo. Lo mismo en inglés.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! abrazo
