### ISSUE TITLE
Pequeñas Correcciones Versión en Inglés Tarifario (tranqui, para el lunes)

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#44]
Son correcciones de texto nada más.

Donde dice en ingles

```
• Amounts in USD all taxes included
```

cambiar 

Prices in USD all taxes included

Donde dice

Suite of 3 bedrooms

por

 Three bedrooms Suite

Donde dice

All house for exclusive use

cambiar a 

Whole house for exclusive use

Day Use$100

```
• Includes 3 course lunch, glass of Wine, Mineral Water
• Afternoon tea or House Cocktail (passenger's choice)
• Beach service
• Kayaking
```

All Inclusive Service

```
• Transfer In / Out ( Colonia )
• Breakfast
• 3 steps lunch
• Afternoon + tea
• Cocktail Hour (with Housemade Cocktails)
• 7 steps dinner
• House Wine included in Lunch & Dinner
• Non alcoholic drinks
• Beach service
• Kayaking
• Electric bikes
• Assurances
```

cambiar a 

All Inclusive Service

```
• Transfer In / Out ( Colonia )
• Breakfast
• 3 steps lunch
• Afternoon + tea
• House Cocktail
• 7 course dinner
• House Wine included in Lunch & Dinner
• Mineral water
• Beach service
• Kayaking
• Electric bikes
```

7 step Dinner & wine testing $100

Non alcoholic drinks, cocktails & house wine included

cambia a

7 Course Dinner  $100

House Cocktail, Mineral water and house wine included

donde dice Bebidas sin alcohol hay que cambiarlo a Agua mineral

En el precio del day use , 

```
• Incluye Almuerzo 3 Pasos con Vino de la casa
```

que cambie

```
• Incluye Almuerzo 3 Pasos, copa de Vino, Agua Mineral
```

se elimina:     • Bebidas sin Alcohol

```
• Merienda
• Cocktail Hour (con Cocktail de la casa)
```

pasa

```
• Merienda o Cocktail de la casa a elección
```

en el day use corporativo, (tanto ingles como español)  el precio esta mal ubicado y le falta el signo $
Uso living room con proyector HD pantalla de 3.5 m de ancho. Hasta 6 Pax 800

Sacar el titulo Minors Policy 

y cambiar:

```
• Rio Ancho is intended for over 12 years
```

a

```
• Rio Ancho is reserved for guests older than 12
```

abrazo

**Comment by braulio-evangelisti** [comment]
Corregido

**Comment by LeandroBraier** [comment]
Gracias!
