### ISSUE TITLE
Newsletter Simple "Promo Calzados California"

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#45]
Fede, te paso por mail logo de Calzados California. Lo que necesitamos es armar un newsletter muy simple con la estética de Calzados California (colores y logo, las fuentes que sean normales y combinen nada más). Es una promoción de Río Ancho para ellos. El texto sería el siguiente:

SUBJECT: Conocé Río Ancho en Uruguay- Beneficio Exclusivo para clientes de Calzados California

BODY:

TITULAR: LATE CHECK OUT + ALMUERZO EXTRA PARA DOS

FOTOS: La del Atardecer que aparece en filosofía bien grande. Debajo 3 fotos chiquitas, una de Lodge, una de Carta y una de Programas.

TEXTO DESCRIPCIÓN: En uno de los mejores y más exclusivos Lodge de la Costa Uruguaya. Ubicado en un entorno único, a orillas del Rio de la Plata y a pocos km de Colonia del Sacramento. La visión franca al río, atardeceres únicos, playas de arenas blancas, el silencio propio del lugar y una naturaleza que puede contemplarse desde todos los espacios de una casa gourmet en todo sentido, atendida por sus dueños. \* **

Solicitalo ahora haciendo clic aquí (este link lleva al mail info@rioanchocolonia.com y el subject es: Promoción Especial Clientes Calzados California)

(Esto que va a continuación bien chiquito)
- Sólo para reservas confirmadas antes del 31 de agosto.
  *\* Se excluye el período de vacaciones de invierno y fin de semana largo (debi agregar lista)

Armalo en HTML como el de Klaukol y listo. Lo manda otra gente.

abrazo

**Comment by LeandroBraier** [comment]
Fede, ya te subí el newsletter a la carpeta RIO ANCHO MAQUETADOR EN DROPBOX. Está en PSD, versión editable y versión rasterizada. Lo podremos tener listo en HTML para hoy a la tarde?

Confirmame por favor.

abrazo

**Comment by FAAREIA** [comment]
Si no hay drama Lea.
La parte de:
Solicitalo ahora haciendo clic aquí (este link lleva al mail info@rioanchocolonia.com y el subject es: Promoción Especial Clientes Calzados California)
Que yo sepa, no es posible que te autcomplete el subject de tu progama de correo electrónico. Lo que haría es que te lleve a la sección de contacto, y lo que habría que hacer es que te autocomplete el asunto.

**Comment by LeandroBraier** [comment]
Preguntale a Marce. Creo que se puede hacer eso. En algún lado lo hicimos.

Sino que directamente al hacer clic en el botón envíe a esa dirección y con
ese subject desde la dirección de mail del usuario, ¡sin que el usuario lo
tenga que completar y enviar. Se puede eso?

Faltaría el link a la web de Rio Ancho al pie no?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-28 11:00 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/mailing/calzados-california/calzados-california.html

Ahi le agregué el link al sitio en el logo de abajo de todo ;)

**Comment by LeandroBraier** [comment]
Buenisimo. Lo presento, pero anticipando lo que me pueden consultar.

Es mucho laburo hacer el texto editable?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Si es laburo, unas 2hs o más teniendo en cuenta que seguro haya que cambiar
algun fondo o textura. Igual no tiene sentido que sea editable, excepto que
hagan unas pruebas y siempre pase a spam el newsletter.

2015-05-28 11:23 GMT-03:00 LeandroBraier notifications@github.com:

**Comment by LeandroBraier** [comment]
Perfecto. Solo para saber.

Igual me pidieron una pequeña corrección.

Que el logo de Calzados California linkee a:

http://www.calzadoscalifornia.com.ar/

y que al pie del newsletter, dentro del marco amarillo del color de
Calzados California, diga lo siguiente:

"Conocé nuestras últimas promociones"

y linkee a:

http://www.calzadoscalifornia.com.ar/promociones2012.php?texto=promociones&linea=Novedades

Eso solo. Actualizalo y pasamelo nomás.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-05-28 11:49 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Actualizado:
http://www.rioanchocolonia.com/mailing/calzados-california/calzados-california.html

**Comment by LeandroBraier** [comment]
Perfecto, Fede. Gracias! Ya lo mando, igual te pido un cambio muy chiquito en texto:

Donde dice "otros lugares" cambiar por "otros proyectos".

abrazo

**Comment by FAAREIA** [comment]
Actualizado. Dale F5
