### ISSUE TITLE
Cambiar "Price List" por "Rates" en la versión en inglés del Sitio de Río Ancho. 10/7

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#46]
Solo eso. Si no llegás a hacerlo hoy @FAAREIA pasame el acceso al sitio y lo cambia MS, no hay problema.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti si ves que vos lo podés tomar tomalo porfa.

abrazo

**Comment by FAAREIA** [comment]
Hecho, lo cambié en todos lados

**Comment by LeandroBraier** [comment]
Gracias!
