### ISSUE TITLE
Cambiar Formulario de Reservas por Widget de Booking. DEADLINE: 10/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#47]
Fede, avisame porfa cuando lo hayan podido hacer.

Va el código del widget:

<div id="f2b-widget"><script src="<a href="<a href="http://www.freetobook.com/affiliates/dynamicWidget/js/widget-js.php?w_id=17594&amp;w_tkn=12XrIGCUkRuOE1LALbkBAFgJBtR74VM6n76k01xauMQwf1Vh39u7RYcphxxs1&amp;w_new=1">http://www.freetobook.com/affiliates/dynamicWidget/js/widget-js.php?w_id=17594&amp;w_tkn=12XrIGCUkRuOE1LALbkBAFgJBtR74VM6n76k01xauMQwf1Vh39u7RYcphxxs1&amp;w_new=1</a>"><a href="http://www.freetobook.com/affiliates/dynamicWidget/js/widget-js.php?w_id=17594&amp;w_tkn=12XrIGCUkRuOE1LALbkBAFgJBtR74VM6n76k01xauMQwf1Vh39u7RYcphxxs1&amp;w_new=1</a>">http://www.freetobook.com/affiliates/dynamicWidget/js/widget-js.php?w_id=17594&amp;w_tkn=12XrIGCUkRuOE1LALbkBAFgJBtR74VM6n76k01xauMQwf1Vh39u7RYcphxxs1&amp;w_new=1</a></a>" type="text/javascript"></script></div>

Cualquier duda avisame.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti si ves que vos lo podés tomar tomalo porfa.

abrazo

**Comment by FAAREIA** [comment]
Lea, el código del widget no lo veo. Más allá de eso, no se si llego hoy a implementarlo, si es hiper-simple si.

**Comment by LeandroBraier** [comment]
Frenalo por ahora entonces. Ahora te paso detalles y lo subís el lunes.

Por ahora no saques el formulario que está. A lo sumo agregamos un apartado debajo que diga "Reservar habitación a través de Booking" y ahí pegamos el widget.

Va el código por mail.

**Comment by LeandroBraier** [comment]
Confirmado. Avancemos en una página fuera de producción cómo queda este apartado.

abrazo

**Comment by LeandroBraier** [comment]
Buen día Fede! Cuando podremos ver esto?

**Comment by FAAREIA** [comment]
Ayer ya lo estuve trabajando asi que hoy lo tenemos listo

**Comment by LeandroBraier** [comment]
Genial, gracias Fede!

No te olvides que hoy vamos a estar necesitando estar en contacto a full con vos por el tema del juego. 

Si te vas a tener que ir o estar desconectado de las redes o el teléfono avisame porfa.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta listo Lea, fijate:
http://www.rioanchocolonia.com/reservas2.html

Puede que veas los títulos en ingles y que después cambien al castellano. Si no hay forma de especificarle un idioma, el reemplazo es la única opción.

**Comment by FAAREIA** [comment]
Dale F5.

**Comment by LeandroBraier** [comment]
Buenisimo Fede!

Quedó genial.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Gustó mucho Fede. Pidieron lo siguiente:

**Comment by LeandroBraier** [comment]
Habria que separar claramente las secciones porque no se entiende.

Poner con en el primer recuadro

Hospedaje: Chequeo de disponibilidad en el momento

Y hacer otro recuadro que englobe todo:

Otros Programas:

En ese segundo recuadro, quitaríamos del desplegable de opciones las habitaciones. Las habitaciones solo se reservarían por el widget de Booking.

Esto puede ser para mañana, no es prioridad.

abrazo

**Comment by FAAREIA** [comment]
No hay desplegable con las habitaciones. ¿Vos decis se sacar del formulario de reserva el desplegable de que cosa reservar y el de la cantidad? La fecha y hora lo dejamos?
Cuando decis "un recuadro que englobe todo" te referis a que englobla también el widget?

**Comment by LeandroBraier** [comment]
Me entendiste mal. Dentro del desplegable, hay que sacar el item "Suite 3 habitaciones". Nada más.

**Comment by FAAREIA** [comment]
Ahi les hice una separación para que se distingan, siguiente los estilos del sitio.
Del desplegable saqué "Casa Completa" y "Suite 3 habitaciones"

Espero que guste, avisame también si subo a producción el home con el video.

**Comment by LeandroBraier** [comment]
Casa completa debería quedar, porque es otra cosa en realidad. Incluye
living pileta y todo.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 17:47 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Corregido

**Comment by LeandroBraier** [comment]
Genial, ya quedó entonces!

Subilo a producción nomás.

**Comment by LeandroBraier** [comment]
Cuando lo subas a producción no te olvides de hacerlo en la versión en inglés también.

Aumentale el grosor de la línea que separa ambas parte del formulario ("Hospedaje" de "Otros Programas").

abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/reservas.html
http://www.rioanchocolonia.com/en/reservation.html

**Comment by LeandroBraier** [comment]
Quedó perfecto Fede. Solo cambiá Reservation por Reservations con S final.

abrazo

**Comment by FAAREIA** [comment]
Imagino que el cambio es en el título de la página, ese que aparece en la solapa del navegador. Si es asi, ya esta ;)

**Comment by LeandroBraier** [comment]
Si, gracias Fede. La URL tambien cambiala a reservations y listo, ya estamos.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias!
