### ISSUE TITLE
Nueva Sección de Prensa para la Web de Río Ancho.

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#48]
Fede, necesito armar una sección de prensa en base a esta:

http://awasiatacama.com/en/info/press/list

En cuanto tenga los links te paso.

abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti si ves que vos lo podés tomar tomalo para el lunes porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Hace un rato arranque esto Lea, trato de tener algo listo para el mediodia.

Abrazo

**Comment by LeandroBraier** [comment]
Buenisimo, gracias Braulio!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Lea fijate ahi: http://www.rioanchocolonia.com/prensa.html

No esta linkeado a ningun lado, solo se ve ingresando por la url.

Abrazo

**Comment by LeandroBraier** [comment]
Está excelente Braulio. Quedó muy bueno. Lo muestro al cliente y te doy feedback.

Gracias!

Fijate lo del mailing de bienvenida ahora.

abrazo

**Comment by LeandroBraier** [comment]
Braulio, gustó mucho!

Te pasé por mail los links a las notas. Vas a tener que incluir 

Además, armá dos versiones:

1) En la que lo que se vea sean las tapas de las revistas

2) Otra en la que lo que se vea sean capturas de las notas.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea actualizá ahi que ya subi de las dos versiones la 2. De las 9 notas, 4 solamente encontre la tapa de la revista, y son de la edicion actual, no de la de la fecha del articulo. Mañana avisame si queres que ponga mitad con tapas y mitad capturas,dejo todo como esta, o sabes donde conseguir el resto de las tapas.

http://www.rioanchocolonia.com/prensa.html

Abrazo

**Comment by LeandroBraier** [comment]
Quedó muy bueno Braulio!

Hagamos así entonces:

1) Como thumbnails poné todas capturas de la nota nomás, pero recortada así:

<img width="708" alt="captura de pantalla 2015-07-13 a la s 21 46 49" src="https://cloud.githubusercontent.com/assets/6719872/8663958/5ec44a30-29a7-11e5-8fbb-bd5f22a70f22.png">

Más centrado en título del medio, titulo y foto, no tanto texto abajo.

2) En lugar de link, poné una captura completa de la nota en formato PDF, así aunque el medio después lo borre lo seguimos teniendo.

Esto puede ser para mañana sin problema. Al mediodia está bien.

abrazo

**Comment by braulio-evangelisti** [comment]
Fijate ahora Lea.

**Comment by LeandroBraier** [comment]
BUenisimo Braulio!

Gracias! Lo muestro.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
@braulio-evangelisti te comparto por gmail las tapas y notas internas a subir en esta sección. Solamente dejá el link a la nota web, pero la captura debe ser de estas, de la nota impresa:

https://drive.google.com/folderview?id=0B9DM7B0QVVYLfnY0VFNzc2RTMEYyVEZ1MlBXaE9pVldad0NfajRpb0RaNXRiSXhPcW5OdVk&usp=sharing_eid

Confirmame si lo podés tener para el miércoles.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea las tapas de noticias, planeta urbano y lugares se corresponden con las notas que estan subidas.

1- me pasaste en otro lado otras notas a subir para las demas tapas?
2- Las capturas internas de las notas donde las pongo?

Abrazo

**Comment by LeandroBraier** [comment]
En realidad lo que te pido hacer es reemplazar las notas subidas (que son capturas de la nota online) por estas que te mando, es decir, fotos escaneadas de la revista gráfica impresa. Confirmame si estamos bien con eso, me parece que no fui claro en el pedido.

abrazo

**Comment by braulio-evangelisti** [comment]
Ah estas hablando del contenido de los PDF a descargar. Ok. Agrego la del Gourmet y Magna que no estaban subidas.

**Comment by LeandroBraier** [comment]
Perfecto. Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by braulio-evangelisti** [comment]
Tengo todo armado en local pero el sitio esta como caido o no puedo acceder desde mi ftp, apenas este online de nuevo subo todo.

Sigo con Klaukol

Abrazo

**Comment by braulio-evangelisti** [comment]
Ahi tendria que estar. Avisame cualquier correccion, las fechas no las tenia eso seguro hay que acomodar.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!! Chequeo con el cliente y te confirmo.

abrazo

**Comment by LeandroBraier** [comment]
@FAAREIA necesitamos dos cosas:
1. Subir urgente al menú del sitio la página de prensa. En castellano al menos.
2. Subir para mañana o pasado un nuevo artículo de revista a la sección de prensa.

Revista: Cosmopolitan. 
Fecha: Noviembre 2015

![datos adjuntos sin titulo 01320](https://cloud.githubusercontent.com/assets/6719872/10894092/3114a972-818b-11e5-805a-3d3e464923ae.jpg)
![datos adjuntos sin titulo 01323](https://cloud.githubusercontent.com/assets/6719872/10894095/329c8ca6-818b-11e5-9de0-d50a1a6e35ee.jpg)
![datos adjuntos sin titulo 01326](https://cloud.githubusercontent.com/assets/6719872/10894098/3745d956-818b-11e5-8977-1eed5351cdd2.jpg)

Braulio sabe como hacer esto, cualquier cosa me consultan.

abrazo

**Comment by FAAREIA** [comment]
@braulio-evangelisti

**Comment by braulio-evangelisti** [comment]
:+1:

**Comment by braulio-evangelisti** [comment]
Listo!

**Comment by LeandroBraier** [comment]
Gracias Brau! Habrá posibilidad de ordenar las notas de más nuevas a más vieja? Para que siempre se vean primero las más nuevas.

**Comment by braulio-evangelisti** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Excelente! Gracias Brau!
