### ISSUE TITLE
Más cambios de texto en la versión en inglés de la web. DEADLINE: 13/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#49]
SECCION LODGE

Donde dice "surface" cambiar por 

area

Donde dice "Divided Bathroom" cambiar por 

Compartimentalized Bathroom

Donde dice "View of the pool, the hills and the Río de la Plata" cambiar por

View of the pool, the native forest and the Río de la Plata

SECCION MENU
http://www.rioanchocolonia.com/en/menu.html

Donde dice "Rio Ancho Gourmet Lodge opens its doors to honor its guests.
The magic in our cooking gets its inspiration from the best produce our local producers bring to the table. Their orchards, meats, cheeses and fisheries are invoked to offer a seven-dish menu."

cambiar a

“Our menu comes from honoring the producer, the picker, the laboring countryman; communicating the native product and its preparations, of burrowing into the ground to find the roots of the cultures that inhabited the lands, transforming these experiences into a cuisine of influences. Their orchards, meats, cheeses and fisheries are invoked to offer a seven course menu.

Donde dice "Rio Ancho Gourmet Lodge’s menu is a journey through the best native and exotic products we have found in the region and an experience unique to it. Our proposal reflects our consideration for our vegetarian diners as well as our omnivores. Everyone is welcome at our table.

cambiar a

Rio Ancho Gourmet Lodge’s menu is a journey through the best native and exotic products we have found in the region and an experience unique to it. Our proposal reflects our consideration for our vegetarian diners as well as for the omnivores. Everyone is welcome at our table.

Donde dice "It all begins with an appetizer and our freshly-kneaded bread, and follows with the cream soup that prepare us to receive the third step: the entree.

cambiar por

It all begins with an appetizer and our freshly baked bread, following with the cream soup that prepare us to receive the third course.

Donde dice "In our mission to discover new textures; the catch of the day and the homemade pasta will follow, and the next course will be an exquisitely cooked meat or vegetable dish.
The suggestive confectionery ends with tea or coffee, served with petit fours.

cambiar a 

In our mission to discover new textures; the catch of the day or the homemade pasta will follow, and the next course will be an exquisitely cooked meat or vegetable dish.
Then a lavish dessert bringing the journey to and end with one of our custom tea blends or premium coffees, served with petit fours.

Donde dice "Our proposal involves wines and soft drinks. Rio Ancho offers a special wine cellar to discover the wines that Uruguay has to offer and delight with.

cambiar a

Rio Ancho offers a special wine cellar to discover the wines that Uruguay has to offer and delight with.

SECCIÓN FILOSOFIA

Donde dice "Out of a horizon of unforgettable experiences, Rio Ancho Gourmet Lodge was born. Located in a unique setting on the shores of the Rio de la Plata river and a few miles away from Colonia del Sacramento, Uruguay. The grand view to this immense river is our seal. We invite you to enjoy unique sunsets, a private beach and the site’s own silence. The surrounding nature begs to be enjoyed and contemplated from every room in a house run by its owners.

cambiar a 

Out of a horizon of unforgettable experiences, Rio Ancho Gourmet Lodge was born. Located in a unique setting on the shores of the Rio de la Plata river and a few miles away from Colonia del Sacramento, Uruguay. The grand view to this immense river is our trademark. We invite you to enjoy unique sunsets, a private beach and the site’s own silence. The surrounding nature begs to be enjoyed and contemplated from every room in a house run by its owners.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede!

abrazo
