### ISSUE TITLE
Formulario de Reservas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#5]
Fede, te quedó pendiente esta parte del formulario. Te lo pongo en este ticket aparte:

"Lo de la fecha no lo cambié, si lo hago el campo va a quedar muy largo, y tendría que retocar el archivo que envia el email y probarlo."

Ok, probemoslo hoy y busquemos la forma de poner ese desplegable.

abrazo

**Comment by LeandroBraier** [comment]
Perdón, Fede. Lo revisé de nuevo y está bien el formulario como está. Simplemente probemoslo a ver si funciona. A donde está redireccionando en este momento? Así lo probamos.

**Comment by LeandroBraier** [comment]
Urgente porfa, estoy probando el botón del formulario y no parece responder.

**Comment by LeandroBraier** [comment]
Ahí lo pude hacer andar, es el código de seguridad, que si fallás la primera vez ya no te da segunda oportunidad con el mismo código. Cambiemos eso por favor y agreguemos un pop up de respuesta que diga lo siguiente:

"Gracias por solicitarnos tu reserva en Río Ancho Gourmet Lodge. Revisá tu casilla de email para confirmar el proceso. ¡Te esperamos!"

**Comment by FAAREIA** [comment]
A mi no me hace ese comportamiento Lea, no manda el formulario si no pongo bien el código.
Si te recarga la página, el código va a ser diferente.
Lo que si hice es que el código no sea una matemática para resolver , sino un código para tipear.

Ya esta listo el mensaje de OK. Dale ctrl+F5 a la página de reservas.

**Comment by FAAREIA** [comment]
El mail va a abenteveotv@gmail.com

**Comment by LeandroBraier** [comment]
Perfecto, gracias! A mi tampoco me lo envía con código incorrecto. A lo que me refiero es que si fallé la primera vez, por más que la segunda escriba bien el código no me lo envía. Tengo que recargar el código (no la página) y poner el nuevo.

Me parece bien el código actual. Quedó bien el formulario. Ahora tenemos que trabajar en el mailing que le llega a la gente, no? Eso se lo pido a MK?

**Comment by FAAREIA** [comment]
El mail del formulario de reserva lo envia el sistema mismo. Si queres meter alguna frase decime. Si le queres meter gráfica habría que verlo con MK

**Comment by LeandroBraier** [comment]
Ah, entonces hay algun problema porque no me llegó ningun mail por ahora.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-20 10:18 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
En spam no?

**Comment by FAAREIA** [comment]
Capas que porque pusimos cualquier dato, te lo manda a spam. Si lo completas con datos reales, seguramente no vaya a spam

**Comment by LeandroBraier** [comment]
Nop, ni siquiera en spam los recibí.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Ahi mandé un mail real.
Algunos mails con datos re-chamuyo ni llegan a spam

**Comment by LeandroBraier** [comment]
Perdón! Nos estábamos interpretando mal mutuamente. Yo me refería a que no recibí ningun mail como cliente que hizo la reserva. Los mails a la casilla benteveotv@gmail.com los recibí todos, los mios, los de marce, los tuyos, todo. Me refería a un mail que le avisé al cliente que la reserva se efectuó. 

Igual me quedo con el ticket. Dejame que lo consulto con MS primero si por ahí prefieren manejarlo todo ellos desde mails personalizados.

abrazo

**Comment by FAAREIA** [comment]
Ok, avisa

**Comment by LeandroBraier** [comment]
Confirmado. Redirigilo a info@rioanchocolonia.com y listo. Nos desentendemos de eso por el momento.

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

**Comment by LeandroBraier** [comment]
Cambio, Fede. Porfa ahora redirigilo a: ms@rioanchocolonia.com

abrazo

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Perfecto, gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
