### ISSUE TITLE
Sound Cloud Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#50]
Fede, tendríamos que agregar el link al SoundCloud de Río Ancho como red social.

Además, podríamos sumar un embed con una playlist de "música original" de Río Ancho.

Donde decís de incluir el embed? En Filosofía?

**Comment by FAAREIA** [comment]
En Filosofía para mi no hay espacio, aunque creo que podría ser el único lugar conceptualmente "válido" para meter un player. Si queres pasame el código y veo donde meterlo.

**Comment by LeandroBraier** [comment]
Dale. Cuando tenga subidos los tracks te los paso.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-14 9:31 GMT-03:00 Federico Arena notifications@github.com:
