### ISSUE TITLE
Pequeño Restyling Filosofia Rio Ancho. 15/07

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#51]
Fede, necesito una propuesta (no en producción) de cómo quedaría este video como fondo de esta sección en lugar del slideshow que hay ahora en FIlosofía.

https://www.wetransfer.com/downloads/73c2c52d8b754578ad0d95bbc1057e4520150713012247/ffa35319567422186ebd74326c384ff220150713012247/325d88

**Comment by FAAREIA** [comment]
Lo necesitaría sin música

**Comment by LeandroBraier** [comment]
Ok, te lo paso en un rato.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Ahi te lo paso por WeTransfer Fede!

Avisame si está OK el codec.

abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com/index2.html

**Comment by LeandroBraier** [comment]
Buenisimo!

Por qué queda sobre blanco el widget de Trip Advisor? No se puede poner en
una capa encima? como en la página de Francisco?

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Queda sobre el video el widget y su fondo blanco es porque viene asi. Lo de la capa no lo entendí

**Comment by LeandroBraier** [comment]
Me refiero a que no quede esa columna blanca a la derecha, que el Widget queda flotando sobre el video también y ocupe todo el ancho de la web.

![captura de pantalla 2015-07-15 a la s 13 58 55](https://cloud.githubusercontent.com/assets/6719872/8704227/1ed1c40a-2af8-11e5-9976-e6b244090d8b.png)

**Comment by LeandroBraier** [comment]
Buen dia Fede!

Podremos ver esto hoy?

**Comment by FAAREIA** [comment]
Acabo de abrir el safari en MAC y lo veo bien. Le diste F5 para que actualice el CSS?

**Comment by LeandroBraier** [comment]
Perdón, Fede. Lo veo bien. Se ve que lo tenía muy expandido al navegador, si lo achico se superpone perfecto.

Lo muestro a MS y te digo. Seguro me va a pedir que el borde blanco de la derecha sea verde, pero por ahora esperemos a ver qué dice.

abrazo y gracias!

**Comment by FAAREIA** [comment]
Ok, fijate otra vez porque aun expandido se tiene que ver de ancho a ancho el video. Dale al botón de refresh si el F5 parece que no refresca

**Comment by LeandroBraier** [comment]
Es cierto. Ahora lo veo perfecto.

Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-16 9:26 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Fede, está aprobado. Subamoslo a producción pero en mobile no se ve bien. Se puedeadaptar a responsive? Sino la mobile habría que dejarla como antes porque no queda bien como está.

En todo caso un boton al costado de play video. Qué decís?

**Comment by FAAREIA** [comment]
No estaba adaptado aún. Ahi se ve bien en todas las resoluciones.

**Comment by LeandroBraier** [comment]
Genial, gracias Fede!

Ya te confirmo así lo subimos a producción.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, me dice MS que no lo ve bien en su iPhone. Mirá:

![rio ancho responsive falla 1](https://cloud.githubusercontent.com/assets/6719872/8748764/0f0a6bf4-2c73-11e5-9643-42e9e48eca7a.png)

abrazo

**Comment by FAAREIA** [comment]
Solucionado, habría que ver si le puede dar play ahora que esta chico y el texto esta encima del video =/

**Comment by LeandroBraier** [comment]
Lo consulto con MS y te confirmo.

Me avisás cuando subiste el nuevo SWF de Klaukol porfa?

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 14:52 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Marce mandó un cambio

**Comment by LeandroBraier** [comment]
Si, pidió sacar una línea. Yo ya envié eso corregido en mi último mail.
Bajate ese SWF que ya está corregido.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, me dijo MS que para Mobile dejemos la versión anterior y para Web la versión con el video. Se puede eso?

Porque lo sigue viendo mal en mobile.

**Comment by FAAREIA** [comment]
Mmmm si se puede, va a ser pesado nomás. El tema con el video mobile es que no escala como una foto cuando hay que mantener ciertos altos y anchos mínimos.

**Comment by LeandroBraier** [comment]
Por eso, resolvamoslo de la manera más fácil posible, pero la prioridad es
Juego y Torneo de Klaukol.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 16:22 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Ahi esta listo. Que le haga un refresh para verlo. Desde 768px se ve el video, antes el slideshow.

**Comment by LeandroBraier** [comment]
Excelente. Gracias Fede!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by LeandroBraier** [comment]
Fede, MS sigue sin verlo bien. Pongamos la versión anterior en mobile y
listo. El video va solo en versión web.

Cuando lo tengas subilo a producción ya.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-17 16:35 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by FAAREIA** [comment]
Ahora en mobile no se ve el video, solo el slideshow. En tablet o PC se ve el video. Si la tablet es apple, probablemente le tenga que dar play al video.

**Comment by LeandroBraier** [comment]
Ok, le aviso.
 Gracias!
