### ISSUE TITLE
Detección de Origen en la Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#52]
@mkreyness Podemos detectar en que pais está el usuario y poner el telefono de acuerdo a eso ?

**Comment by mkreyness** [comment]
Del IP, mas o menos, nunca es 100% seguro, la gente puede usar proxies que esten en otros paises para navegar.

**Comment by LeandroBraier** [comment]
Ok, MK. Probemoslo.

SI ESTAN EN URUGUAY: +598 4520 2205 (Uruguay)
SI ESTAN EN ARGENTINA +54 11 5254 4381 (Buenos Aires)
SI ESTAN EN EUROPA MENOS UK +34 91 198 1933 (Madrid, Spain)
SI ESTAN EN UK +44 203 318 3875 (London, UK)
RESTO DEL MUDO +1 415 766 9806 (San Francisco: Central de USA)

abrazo

**Comment by LeandroBraier** [comment]
Puede ser para mañana, tranqui. Hoy prioridad Juego Flash, que aun estamos corrigiendo lo que nos pediste.

**Comment by mkreyness** [comment]
Ni idea en que pagina tiene que ir eso, hago una funcion javascript que devuelva eso y que Fede o Braulio la pongan donde corresponda.

**Comment by LeandroBraier** [comment]
Dale, no problem.

**Comment by LeandroBraier** [comment]
Dale, me parece bien.

abrazo

**Comment by LeandroBraier** [comment]
@mkreyness ya está listo esto para que lo agarre @FAAREIA ?

**Comment by mkreyness** [comment]
No, nunca me puse con esto. Esta noche lo veo y les aviso.

**Comment by LeandroBraier** [comment]
No hay tanto apuro MK. Tranqui, puede ser en la semana.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-08 19:12 GMT-03:00 mkreyness notifications@github.com:

**Comment by mkreyness** [comment]
Ya esta todo inventado, Fede fijate este codigo

http://jsfiddle.net/zK5FN/2/

y de ahi tomas response.country y haces lo que sea necesario segun el pais.

**Comment by FAAREIA** [comment]
En Firefox no me funciona =/
IE y Chrome si

Esto del teléfono aplica a reservas y contacto?
Por otra parte, cómo vamos a detectar a todos los paises de europa excepto UK, del "resto del mundo"?

**Comment by mkreyness** [comment]
Te da algun error con Firefox ? Capaz haya que hacerle alguna minima adaptacion.
Para saber "Europa", no queda otra que tener una lista de paises supongo, nadie devuelve un dato de "continente".

**Comment by FAAREIA** [comment]
Ningun error

**Comment by mkreyness** [comment]
A mi me anda bien el jsfilddle ese que te pase, muestra estos datos de mi:

Client side IP geolocation using ipinfo.io
IP: 190.195.49.158
Location: Buenos Aires, Distrito Federal
Full response:

{
    "ip": "190.195.49.158",
    "hostname": "158-49-195-190.cab.prima.net.ar",
    "city": "Buenos Aires",
    "region": "Distrito Federal",
    "country": "AR",
    "loc": "-34.6033,-58.3816",
    "org": "AS10481 Prima S.A.",
    "postal": "1871"
}

**Comment by mkreyness** [comment]
Con un firefox recien instalado. Capaz tenes que actualizarlo ?

**Comment by FAAREIA** [comment]
Voy a ver la config. puede ser eso, yo lo tengo retocado.

**Comment by FAAREIA** [comment]
Esto se aplica a reservas y contacto no?

**Comment by mkreyness** [comment]
Yo ni idea, eso velo con Leandro.

**Comment by LeandroBraier** [comment]
A reservas si. A contacto no.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
No sería más fácil entonces poner todos los números de teléfono como en contacto entonces? Asi también mantenemos una coherencia, en contacto estan asi.

**Comment by LeandroBraier** [comment]
No, justamente por eso me pidieron todo este tema de detección de origen.
Para que llamen solo al que está más en su área y que le salga más barato
consultar para reservar.

En contacto está biwn que esté así para que en algun lado estén todos los
teléfonos.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-08-10 11:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Hecho:
http://www.rioanchocolonia.com/reservas.html

**Comment by LeandroBraier** [comment]
Buenisimo Fede! Gracias!

A donde lleva el link del teléfono?

**Comment by FAAREIA** [comment]
a ningun lado, si haces click con el celular, llama al teléfono

**Comment by LeandroBraier** [comment]
Perfecto entonces. Gracias Fede!
