### ISSUE TITLE
El video no aparece en la home

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#53]
Fede, fijate si te pasa lo mismo. Pruebo en distintos navegadores y el video no aparece, no despliega.

Le doy F5, reinicio el wifi, todo. Tengo 6 mb de velocidad pero no lo reproduce.

**Comment by LeandroBraier** [comment]
@FAAREIA porfa demosle prioridad a esto. abrazo

**Comment by LeandroBraier** [comment]
@braulio-evangelisti si podés, revisás qué pasa con esto? Yo lo sigo viendo así.

<img width="1680" alt="captura de pantalla 2015-07-20 a la s 09 27 05" src="https://cloud.githubusercontent.com/assets/6719872/8775580/e6e66854-2ebf-11e5-88fd-db30327f8b55.png">

**Comment by braulio-evangelisti** [comment]
Actualizá y fijate ahora Lea.

Abrazo

**Comment by LeandroBraier** [comment]
Ahora si Brau!! Qué pasaba al final?

abrazo

**Comment by braulio-evangelisti** [comment]
Faltaba pasarlo a producción una vez que estuviera andando bien y con todos los detalles definidos el index con el video y el slider en celulares :+1:

**Comment by LeandroBraier** [comment]
Excelente! Gracias!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2015-07-20 10:16 GMT-03:00 Braulio Evangelisti notifications@github.com:
