### ISSUE TITLE
Pequeño cambio de texto en Sección Tarifas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#54]
BRaulio, es muy simple.

Donde dice:

Casa completa           Hasta 8 pax con pensión completa. Todos los ambientes en exclusiva     $2500
Suite de 3 habitaciones          Hasta 6 pax con pensión completa   $1600

Que diga…

Casa completa           Hasta 8 pax con servicio all inclusive. Todos los ambientes en exclusiva              $2500
Suite de 3 habitaciones          Hasta 6 pax con servicio all inclusive                       $1600

abrazo

**Comment by braulio-evangelisti** [comment]
Buen día Lea. Ahí aplique los cambios en el tarifario.

Abrazo

**Comment by LeandroBraier** [comment]
Buen día Brau! Gracias! abrazo
