### ISSUE TITLE
JQuery en Página de Reservas

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#55]
Fede, para la pagina de reservas , se puede poner un date time picker que tenga un UI similar al de reservas de habitaciones ?

http://www.jqueryrain.com/demo/jquery-date-time-picker/

Confirmame porfa.

abrazo

**Comment by braulio-evangelisti** [comment]
Lea fijate ahora el diseño del datepicker mas acorde al sitio.

**Comment by LeandroBraier** [comment]
Quedo perfecto Brau. gracias!! abrazo
