### ISSUE TITLE
Error en Teléfonos Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#57]
Brau, por qué se ven así los teléfonos? Desde capital me da ese numero pero repetido 4 veces:

<img width="1239" alt="captura de pantalla 2015-09-01 a la s 22 59 34" src="https://cloud.githubusercontent.com/assets/6719872/9621324/8ed1ca7e-50fb-11e5-909b-93e42c6ad478.png">

Qué pacho?

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia Lea 
deduzco por #52 que en reservas solo tiene que haber un teléfono según ubicación y en contacto todo el listado. 
Aparecía así porque todos tenían la misma clase y reemplazaba en todos los tag el contenido. Fijate si así era como estaba antes "telefono (ubicacion)"
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Brau!!

abrazo
