### ISSUE TITLE
Pequeña modificación de texto en Sección Tarifas. 14/09

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#58]
Buen día @braulio-evangelisti !

Solo te pido por favor cambiar donde dice Pax por huéspedes. Es en la quinta y sexta fila de la primera tabla.

http://www.rioanchocolonia.com/tarifas.html

abrazo

**Comment by braulio-evangelisti** [comment]
Buen dia lea. Termino los cambios de las bases en Torneos y hago este.

Abrazo

**Comment by braulio-evangelisti** [comment]
Listo.

**Comment by LeandroBraier** [comment]
Gracias Brau!
