### ISSUE TITLE
Cambios en la web de Rio Ancho 31/12

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#59]
@FAAREIA cómo va? Muchas felicidades!

Sin apuro te paso un pedido para el jueves. El chef Molteni deja de trabajar con Río Ancho, por lo cual habría que quitarlo de la web. Para esto te detallo el cambio:

SECCIÓN FILOSOFÍA

Quitar foto y texto del Chef Molteni que aparece debajo de la foto principal. También su biografía.

abrazo

**Comment by braulio-evangelisti** [comment]
Hecho!

**Comment by LeandroBraier** [comment]
Gracias @braulio-evangelisti !
