### ISSUE TITLE
Metadata Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#6]
Fede, pongamosle la metadata:

Título de la página: Río Ancho Colonia Gourmet Lodge

Descripción: Rio Ancho, Gourmet Lodge, es un restaurant gourmet con alojamiento en un exclusivo lodge que se emplaza en una zona rural a 10 km del Centro Histórico de Colonia del Sacramento y a orillas del Río de la Plata.

metatags: colonia, uruguay, hotel, restaurant, río de la plata

**Comment by FAAREIA** [comment]
Habría que poner eso distinto en cada página. Tiene que ser distinto porque cada página habla de algo diferente y sino creo que podría ser spam

**Comment by LeandroBraier** [comment]
Entiendo. Subí este que te pasé para la Home y te paso ahora uno distinto
para cada una.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-20 10:27 GMT-03:00 Federico Arena notifications@github.com:

**Comment by LeandroBraier** [comment]
Menú/ Río Ancho

El menú de Rio Ancho Gourmet Lodge está concebido agasajar mediante un momento mágico. .
Es un menú experiencia de siete pasos, inspirados en lo mejor que nos puede brindar la estacionalidad, las huertas, los paisanos, los pescadores de este paraje en la costa de Colonia, Uruguay.

Metatags: menú, estación, huerta, pescadores, uruguay

Programas/ Río Ancho

Organizamos la experiencia de Río Ancho Gourmet Lodge en distintos programas: Almuerzo + Distensión, Tardes + Té, Atardeceres + Cocktails + Cena + Lodge + Desayuno, Programas de Contenido y Eventos corporativos y sociales.

Metatags: almuerzo, merienda, cena, cocktails, desayuno, eventos.

Reserva/ Río Ancho

Hacé tus reservas para cualquier cantidad de personas en cualquiera de nuestros programas. Rio Ancho, Gourmet Lodge se emplaza en una zona rural a 10 km del Centro Histórico de Colonia del Sacramento y a orillas del Río de la Plata.

Metatags: Reservas, río ancho, gourmet lodge

Filosofía/ Río Ancho

De todos los momentos inolvidables vividos en familia y entre amigos, a lo largo de los años nace Rio Ancho Gourmet Lodge. Ubicado en un entorno único, a orillas del Rio de la Plata. La visión franca desde Colonia, Uruguay a este inmenso río es nuestro sello. Te invitamos a disfrutar del amplio horizonte, compartir la alegría de cuidar y enriquecer un pedazo de este planeta.

Metatags: río ancho, gourmet lodge, filosofía, uruguay

Contacto/ Río Ancho

Escribinos tus inquietudes directamente aquí. Rio Ancho, Gourmet Lodge se emplaza en una zona rural a 10 km del Centro Histórico de Colonia del Sacramento y a orillas del Río de la Plata. Dirección: Tula Suarez de Cutinella s/n, Paraje El Caño, Colonia del Sacramento. Teléfono: +598 4520 2205

Metatags: río ancho, gourmet lodge, contacto, dirección, teléfono

**Comment by LeandroBraier** [comment]
Fede, recibiste esto no?

**Comment by FAAREIA** [comment]
Lo agrego ahora con lo de rio ancho

**Comment by LeandroBraier** [comment]
Genial.

**Comment by FAAREIA** [comment]
Hecho.

**Comment by LeandroBraier** [comment]
Gracias!
