### ISSUE TITLE
Pequeñisima modificación en Tarifas de la web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#60]
Buen día @braulio-evangelisti ! Necesito solo modificaciones de texto aquí:

Day use USD 120,- (actualmente dice 100)

<img width="645" alt="captura de pantalla 2016-01-25 a las 10 59 43 a m" src="https://cloud.githubusercontent.com/assets/6719872/12552361/2678c140-c350-11e5-9cb3-e44cd773fd2d.png">

Cena 7 pasos USD 120,- (actualmente dice 100)

<img width="1249" alt="captura de pantalla 2016-01-25 a las 10 59 39 a m" src="https://cloud.githubusercontent.com/assets/6719872/12552364/2aaeda1a-c350-11e5-97ef-41b1a0cdd93f.png">

Almuerzo Adicional para PAX en tránsito (3 pasos) USD 60,- (actualmente dice 50)

<img width="489" alt="captura de pantalla 2016-01-25 a las 11 44 42 a m" src="https://cloud.githubusercontent.com/assets/6719872/12553466/7a7a5a0a-c356-11e5-81cb-72833b4e9444.png">

Recordá hacerlo tanto en versiones en español como en inglés.

**Comment by braulio-evangelisti** [comment]
Hecho!

**Comment by LeandroBraier** [comment]
Perfecto @braulio-evangelisti ! gracias!
