### ISSUE TITLE
Modificaciones en Tarifario Web

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#61]
Buen día @FAAREIA ! Necesito que lo antes posible modifiques estas palabras en el tarifario de la web de Rio Ancho.

Pongo en negrita lo que hay que modificar. 

Servicio All Inclusive **(que diga Servicio Full Board)**

Traslado de ida / de regreso (Colonia)
Desayuno
**Almuerzo y Cena 3 pasos (Incluye Copa de Vino de la Casa)**
**Merienda**
Cocktail Hour (con Cocktail de la casa)
Agua mineral
Servicio de playa
Uso de Kayaks
Uso de Bicicletas eléctricas
Seguros

Servicio Adicionales

Day Use                                                                                                                  120

Incluye Almuerzo 3 Pasos, copa de Vino, Agua Mineral
**Merienda**
Servicio de playa
Uso de Kayaks

Full board Service

Transfer In / Out (Colonia)
Breakfast
**Lunch & dinner 3 courses (Glass of House Wine included)**
**Afternoon tea**
House Cocktail
Mineral Water
Beach service
Kayaking
Electric bikes

Day Use                                                                                                         120

Additional Services
Includes 3 course lunch, glass of Wine, Mineral Water
**Afternoon tea**
Beach service
Kayaking

**Comment by FAAREIA** [comment]
Hecho.
En la tabla que también decia "servicio all inclusive" lo cambie por "Servicio Full Board".
En el html en ingles lo dice de otra forma "full acommodation" por lo que no lo cambié.

Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede! La versión en español está perfecta. La versión en inglés me da error:

http://www.rioanchocolonia.com/en/price-list.html

Cuando esté funcionando avisame y la chequeo.

abrazo

**Comment by FAAREIA** [comment]
Ese link de donde lo sacaste? Avisame asi lo arreglo.
El link es: http://www.rioanchocolonia.com/en/rates.html

**Comment by LeandroBraier** [comment]
Está perfecto el que me pasás Fede.

El link ese lo saqué al ingresar a la versión en inglés desde el Tarifario en sí mismo.

Estoy acá:

<img width="989" alt="captura de pantalla 2016-03-22 a las 11 02 49 a m" src="https://cloud.githubusercontent.com/assets/6719872/13953510/10fbd832-f01b-11e5-81eb-6737ca760cda.png">

y hago clic acá:

<img width="36" alt="captura de pantalla 2016-03-22 a las 11 02 53 a m" src="https://cloud.githubusercontent.com/assets/6719872/13953516/16ebfe34-f01b-11e5-9822-6a2cf31c1894.png">

Corregí ese link porfa. No está solo ahí. En todos los links de la versión en inglés me está llevando a price-list.html, no a rates.html.

abrazo

**Comment by FAAREIA** [comment]
Joya ahi lo corregí de todos los lugares en donde estaba mal, como por ejemplo http://www.rioanchocolonia.com/en/reservations.html

**Comment by LeandroBraier** [comment]
Gracias Fede!! Quedó hecho!! abrazo

**Comment by LeandroBraier** [comment]
Buen día @FAAREIA ! Para el lunes me dieron un detallecito más del Tarifario.

Eliminá de la versión en español la línea que dice:
Cena 7 pasos (Incluye Vino de la Casa en Almuerzo y Cena)

De la versión en inglés:
7 course dinner

abrazo

**Comment by FAAREIA** [comment]
Hecho. Elimine solo la línea que decia lo que marcaste, NO eliminé el detalle de ese menú.
Cualquier cosa avisame
Abrazo

**Comment by LeandroBraier** [comment]
Gracias Fede!! Te confirmo por las dudas.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
