### ISSUE TITLE
Ajustes Tarifas en Español y en Inglés. 19/04

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#62]
@FAAREIA para el lunes o martes necesitaría que apliques modificaciones de contenido en las páginas de Tarifas de la Web de Rio Ancho, tanto en español como en inglés.

Aquí van detallados. Hay ajustes mayores (cambia prácticamente todo el contenido) y otros que son ajustecitos de detalle sobre lo que ya está hoy.

[AJUSTES TARIFARIO RÍO ANCHO 2016-2017 Web español.docx](https://github.com/LeandroBraier/WebRioAnchoColonia/files/221279/AJUSTES.TARIFARIO.RIO.ANCHO.2016-2017.Web.espanol.docx)
[AJUSTES TARIFARIO RÍO ANCHO 2016-2017 Web ingles.docx](https://github.com/LeandroBraier/WebRioAnchoColonia/files/221280/AJUSTES.TARIFARIO.RIO.ANCHO.2016-2017.Web.ingles.docx)

Cualquier duda avisame.

abrazo

**Comment by FAAREIA** [comment]
Si esta OK lo aplico a la versión en ingles.
Hay cosas que no supe como organizarlas y quedaron algo colgadas. Tengan en cuenta que cuanto más organizado y definido me den el documento, más rápido lo hago, sino tengo que organizarlo a mi criterio.
http://www.rioanchocolonia.com/tarifas2.html

**Comment by LeandroBraier** [comment]
No te preocupes, a mi me lo pasaron peor y yo te lo organicé lo mejor que pude. Te confirmo si está OK te confirmo.

abrazo y gracias!

**Comment by LeandroBraier** [comment]
Fede, te paso el feedback exacto:

GENERAL

En los dos lugares donde dice HAB. DELUXE cambiar por DELUXE

<img width="238" alt="captura de pantalla 2016-04-19 a las 3 41 34 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650448/33c6d7da-0642-11e6-9d35-76d16e644774.png">
<img width="358" alt="captura de pantalla 2016-04-19 a las 3 41 42 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650450/357d1008-0642-11e6-9beb-a65c43074694.png">

**TEMPORADA ESPECIAL**

. Pax adicional Full Board (DLX y JrSuite MAX 1, Master Suite MAX 2), ponele el 190 en cada columna. 

<img width="1150" alt="captura de pantalla 2016-04-19 a las 3 37 30 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650312/a56c7080-0641-11e6-91db-dd920ee6c2be.png">

. Esta Casa Completa que está por separado, debe ir como un item más de la primer grilla:

<img width="1200" alt="captura de pantalla 2016-04-19 a las 3 42 55 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650492/607a8e7a-0642-11e6-9db3-802c3afd7f6f.png">

En lugar de "Una habitación" debe decir: "Casa completa, hasta 8 pax, Full Board" de la misma forma que aparece en temporada estival:

<img width="1179" alt="captura de pantalla 2016-04-19 a las 3 43 41 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650518/7445d680-0642-11e6-9145-44c1e7818f75.png">

El orden de la grilla quedaría:

Una habitación
Dos habitaciones
Tres habitaciones
Pax adicional Full Board (DLX y JrSuite MAX 1, Master Suite MAX 2)
Casa completa, hasta 8 pax, Full Board

**TEMPORADA ESTIVAL**

. OJO dice Festival. Sacar la F

. Pax adicional Full Board (DLX y JrSuite MAX 1, Master Suite MAX 2), ponele el 230 en cada columna. 

<img width="1178" alt="captura de pantalla 2016-04-19 a las 3 42 26 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650460/45ec52f0-0642-11e6-96e9-fc0207c31097.png">

. Mover el Pax adicional Full Board a estar como la cuarta fila, como te quedó en la grilla anterior. El orden de la grilla de Temporada Estival quedaría así:

Deluxe, base DBL, Full Board
Junior Suite, base DBL, Full Board  
Master Suite, base DBL, Full Board
Pax adicional Full Board (DLX y JrSuite MAX 1, Master Suite MAX 2)  
Tres Habitaciones hasta 6 pax, Full Board.
Casa Completa, hasta 8 pax., Full Board

**Fechas especiales…..ALOJAMIENTO - Fechas especiales - Navidad - Año Nuevo – Semana Santa** 

. Palabra PRECIO centrarla

. Cambiar Hab Deluxe Base DBL por Deluxe, base DBL, Full Board y lo mismo en las demás habitaciones. El orden de la grilla de Fechas especiales quedaría así:

Deluxe base DBL, Full Board 
Junior Suite base DBL, Full Board
Master Suite base DBL, Full Board
Pax adicional (DLX y JrSuite MAX 1, Master Suite MAX 2)
Suite de tres habitaciones: Hasta 6 pax con servicio Full Board.
Casa Completa: Lodge en exclusiva hasta 8 pax Full Board

**Servicios Adicionales**

Valor de 250, ponerlo en negro y tamaño como el de 120 de menú degustación:

<img width="142" alt="captura de pantalla 2016-04-19 a las 3 49 51 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650733/525ae4c4-0643-11e6-9bf3-ea5c21b61599.png">

**PROGRAMA OUTING DAY CORPORATIVO (LUNES A JUEVES)**

Cambiar el precio…debería decir 1200 y en negrita y tamaño como el de 120:

<img width="142" alt="captura de pantalla 2016-04-19 a las 3 49 51 p m" src="https://cloud.githubusercontent.com/assets/6719872/14650733/525ae4c4-0643-11e6-9bf3-ea5c21b61599.png">

Confirmame si están claros los cambios, sino avisame. Consulté con el cliente por teléfono por las dudas y acá intenté hacerlos lo más claros posibles pero  te lo explico por TEL sino.

abrazo

pd: Si podés aplicar esto mañana genial

**Comment by LeandroBraier** [comment]
@FAAREIA , cuando puedas subí esto porfa. Son detalles rápidos que no te van a llevar ni 10 min.

abrazo

**Comment by FAAREIA** [comment]
Ojalá llevara solo 10m ^^
Ahi creo que esta listo, si esta aprobado ya hago la versión en ingles.
http://www.rioanchocolonia.com/tarifas2.html

**Comment by LeandroBraier** [comment]
Gracias Fede! Yo lo veo perfecto ya subilo a producción en español y
aplicalo en inglés. Yo solo le voy a avisar el cliente que ya está listo y
subido, para que no pida más cambios.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !! Lo veo joya.abrazo
