### ISSUE TITLE
Quitar Foto de Chef Molteni

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#63]
Fede, en la versión en inglés al hacer scroll se sigue viendo una foto que ya sacamos hace tiempo. Apenas puedas quitala.

<img width="1515" alt="captura de pantalla 2016-04-26 a las 11 14 09 a m" src="https://cloud.githubusercontent.com/assets/6719872/14820500/5559de5a-0b9d-11e6-9c37-3acebfbe3e2c.png">

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias @FAAREIA !
