### ISSUE TITLE
Achicar fuente de títulos de sección TARIFA. 12/08

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#64]
@FAAREIA el cliente notó en las tablas de Tarifas de la versión mobile del sitio que los textos traspasan sus respectivas celdas.

![screenshot_2016-08-08-16-07-38](https://cloud.githubusercontent.com/assets/6719872/17493044/00ced22a-5d85-11e6-88e7-1b6b9897d265.png)

Para solucionarlo, (sin apuro) porfa achicá la tipografía de la tabla en la palabra NOCHES y en las cifras de esas filas.

**Comment by FAAREIA** [comment]
Hecho para todas las tablas en la resolución más chica (320px)

**Comment by LeandroBraier** [comment]
Gracias Fede!!!!

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Agencia Productora http://benteveo.tv
Móvil 1158717399
