### ISSUE TITLE
Subir imagen a IMG del Hosting

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#65]
@FAAREIA intentó hacerlo yo. Sé que es una pavada pero no encontré la forma.

Necesito que reemplaces este archivo:

![firma-rio-ancho](https://cloud.githubusercontent.com/assets/6719872/17574062/bfcb9450-5f34-11e6-8c46-421bd175ea4d.jpg)

En esta URL:

**www.rioanchocolonia.com/img/firma-rio-ancho.jpg**

Solo eso. Puede ser para mañana o el viernes tranqui.

abrazo

**Comment by FAAREIA** [comment]
Hecho
