### ISSUE TITLE
Quitar Precio Tarifa Estival de Web Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#66]
@FAAREIA esto es solo sacar contenido de la sección Tarifario, tanto en español como inglés.

Toda la sección que dice "ALOJAMIENTO - Temporada especial del 10 de Abril al 15 de Septiembre"

<img width="1310" alt="captura de pantalla 2016-09-13 a las 4 44 34 p m" src="https://cloud.githubusercontent.com/assets/6719872/18487946/9fcbc52c-79cd-11e6-9276-8a24b94a600b.png">

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias fede!
