### ISSUE TITLE
Sumar Nota a Sección Prensa de Web Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#67]
@FAAREIA porfa mañana agregás esta nota a la sección de prensa de la web?

http://lacitadina.com.uy/2016/11/18/los-secretos-del-camino-tula/

abrazo

**Comment by FAAREIA** [comment]
Fijate si esta ok ahi lea:
http://www.rioanchocolonia.com/prensa.html#mix
El PDF me costó generarlo, tendría que invertigar un poco más para ver como se puede exportarlo en mejor calidad y que el texto sea texto y no imagen. Avisame si esta ok o lo mejoramos

**Comment by LeandroBraier** [comment]
Está muy bien Fede! Si le pudieras sacar las 4 secciones que hablan de los otros hoteles y dejar solo el de Rio Ancho estamos joya.

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Muchas gracias Fede!!! Perfecto! abrazo
