### ISSUE TITLE
Subir SiteMap Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#7]
Fede, necesito que:
1. Subas las versión CON y SIN "WWW" a Google Analytics.
2. Subas el XML del sitemap que te mando por mail a la root de www.rioanchocolonia.com

Cuando la tengas, avisame así subo la url http://www.rioanchocolonia.org/sitemap.xml a la página de Google Webmaster, es decir, a:

https://www.google.com/webmasters/tools/sitemap-list?hl=es&siteUrl=http://www.rioanchocolonia.com/#MAIN_TAB=1&CARD_TAB=-1

**Comment by FAAREIA** [comment]
1- Se elige solo con o sin "www". Si tenes las dos, estas duplicando contenido.
2- En un sitio muy chico, no hace falta subir un xml, ni si quiera hay secciones/articulos nuevos cada semana o mes. Google lo revisa y listo.

**Comment by LeandroBraier** [comment]
Ok.
