### ISSUE TITLE
Pequeños cambios en Web Río Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#8]
Fede, van pequeños cambios URGENTES en el sitio. Sobre todo los dos primeros son prioridad frente a todo lo demás que te pasé. abrazo

SECCIÓN MENÚ
1. Eliminar toda la parte que habla de Precios (dejarla de backup accesible por las dudas, pero ocultarla)

SECCIÓN RÍO ANCHO
1. Que la sección Río Ancho aparezca primero, apenas se abre el site
2. Reducir el texto de Molteni al primer párrafo, dispuesto de la misma forma que el resto de las pantallas del sitio. Debajo del párrafo poner un link que diga: "Biografía"

El texto quedaría así:

Martin Molteni cocina

La cocina está pensada por Martin Molteni, ejecutada bajo su filosofía de honrar al productor, al recolector, al paisano trabajador de su tierra; de comunicar el producto nativo y sus preparaciones, de cavar para encontrar las raíces de las culturas originarias que habitaban estas tierras, convertido estas experiencias en una cocina de influencias.
1. Al hacer clic en el link, que se abra un pop up sencillo con el resto del texto:

Biografía de Martín Molteni
Martin Molteni descubre la cocina en el restaurant de su familia a los 12 años
Realizó sus diplomas de Cocina, y de Pastelería en el Regency Hotel School, de Australia.
Desde los 17 a los 21 años, trabajó en cocinas de hoteles y restaurants de renombre – Lola, Dill, El Aljibe – Sheraton Hotel, La Mansión – Park Hyatt.
Durante 1994 y 1995 se muda a Francia, donde aprende el proceso de tradición, origen y creación de la cocina, principalmente junto a Jacky Dallais, de “La Promenade”.
En 1996 regresa a Argentina, con el propósito de encontrarle una identidad a la cocina local.

Desde su regreso, fue chef de cocina de distintos restaurants, dirigió postítulos de cocina, disertó asiduamente en festivales, exposiciones y seminarios, fue jurado de competencias culinarias, en Argentina y el exterior, y representó a Argentina en numerosos concursos.
Entre 2002 a 2006 fue consultor gastronómico de los Hoteles Boutique Mares Sur.

En 2006 abre PURATIERRA restaurant donde desarrolla su filosofía culinaria, dando forma a una nueva cocina de bases precolombinas en Sudamérica.
Entre sus reconocimientos se encuentra PURATIERRA nombrado mejor nuevo restaurant 2007 en los premios Cuisine&Vins, Martin nombrado Chef del Año 2008 en los premios Tendencias Gastronómicas, en 2013 n°33 de los 50 BEST LATAM en la lista San Pellegrino, y n°50 en 2014.
Opera la planta de CATERING PURATIERRA, y la chocolatería-pastelería de alta gama KAO y es consultor de proyectos hoteleros y gastronómicos para empresas en argentina y el exterior, donde encuentra terreno fértil para plasmar su espíritu.

**Comment by FAAREIA** [comment]
Más urgente que las landing?

**Comment by LeandroBraier** [comment]
Buena pregunta. Si, siempre y cuando con las dos lleguemos para hoy.

**Comment by FAAREIA** [comment]
¿El home del sitio es la sección Río ancho y el home actual lo sacamos por completo?

**Comment by LeandroBraier** [comment]
No, dejemos la sección Inicio como una Sección y pongamos Río Ancho como la primera página que aparece. Te explico: Marce me pidió esto urgente y hay un desorden en pedidos de parte de ellos. Tengo miedo que venga otra persona del Board de Río Ancho y diga: "No, volvemos a como estaba antes" y quiero que esa vuelta sea lo más fácil y rápida posible.

**Comment by FAAREIA** [comment]
jajajaja, que quilomboooooooo.
El tema es que la sección home como la llamamos? Home igual?

**Comment by LeandroBraier** [comment]
Si, Inicio. No te hagas problema por esa desprolijidad. Que la vean ellos así, simplemente me pidieron que la primer página que aparezca sea Rio Ancho, no borrar la otra sección ni cambiarle el nombre, así que por ahora seguimos así. Si me piden algo más te aviso.

Lease: Me están llegando los pedidos de manera desordenada y mi trabajo es resguardarte a vos y a todo el equipo de esa desprolijidad. Por suerte tengo algo de experiencia en eso y estoy amortiguando lo más posible. abrazo

**Comment by FAAREIA** [comment]
http://www.rioanchocolonia.com

**Comment by LeandroBraier** [comment]
Excelente!
1. Los precios siguen estando. Quizá te dije mal. Era en la sección Programas donde hay que borrarlos.
2. Necesito que el texto de Molteni no le tape la cara. Por favor podés alinear el texto y mover la foto levemente hacia la derecha (aunque tengas que escalarla, total la tenés en alta)
3. Al hacer clic en el Menú del Sitio en "Río Ancho" no lleva actualmente a la sección Rio Ancho, esto quedó modificado con este último update. Por favor que vuelva a funcionar.

abrazo

**Comment by FAAREIA** [comment]
Ahi esta actualizado.
Lo que no entendí es el punto 3. En el menú aparece la palabra "Río ancho" que te lleva a la sección "Río ancho" que ahora esta puesta como inicio.

**Comment by LeandroBraier** [comment]
Perfecto. Respecto del 3 intentá ir a la sección Río Ancho una vez que
estás en la sección Menú por ejemplo.

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-23 13:32 GMT-03:00 Federico Arena notifications@github.com:

**Comment by FAAREIA** [comment]
Puedo ir, fijate bien. Dale F5, capas que estas cacheado en algo.

**Comment by LeandroBraier** [comment]
Respecto de Molteni, seguramente va a haber cambios, te los paso en breve.
También estoy esperando el OK para dividir la sección Cena + Lodge +
Desayuno en 2 con dos textos diferentes, por lo cual la foto que quitaste
de Precios seguramente la reincorporemos. Hoy a la tarde te paso eso. Queda
de mi lado por ahora. Gracias!

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

2014-10-23 14:06 GMT-03:00 Leandro Braier leandrobraier@gmail.com:

**Comment by LeandroBraier** [comment]
Fede, dentro de Programas, necesito que dividas la sección Cena + Lodge + Desayuno en estas dos:

Cena + Degustación

A partir de las 21 un nuevo deleite a los sentidos, sobre todo al gusto y el olfato. Nuestros comensales probarán los más elaborados sabores de la cocina regional, preparados por nuestro Chef Gourmet en base a ingredientes e insumos propios de la estación, fruto de la pesca, cultivos y recursos de la zona. Además, una degustación de los mejores vinos para sorprender a los más exigentes.

Lodge + Desayuno

Quienes vienen a cenar y no desean volver al pueblo, contamos con habitaciones de confort para pasar la noche. Al día siguiente despertarán en medio de la calma y la naturaleza, para comenzar con un desayuno reconfortante, teñido de detalles locales.

La imagen de Cena tomá la que tenías en Precios. Para la de Lodge usá la que ya tenías para Cena + Lodge + Desayuno

abrazo

**Comment by FAAREIA** [comment]
Hecho

**Comment by LeandroBraier** [comment]
Gracias Fede! Dos correcciones de texto nomás:

En la parte de Cena, agregar "hs" después de "21". Quizá te lo pasé mal.

En la parte de Lodge, empezar el párrafo agregando la palabra "Para". De
forma que quede: "Para quienes vienen a cenar...

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399

**Comment by FAAREIA** [comment]
Listo, actualizado

**Comment by LeandroBraier** [comment]
Gracias Fede! Te aviso si surge algo más.

abrazo

Leandro Braier
Producción Audiovisual & Social Media
Benteveo Producciones http://benteveo.tv
Móvil 1158717399
