### ISSUE TITLE
SEO de imágenes Rio Ancho

### ISSUE THREAD

**Issue by LeandroBraier** [LeandroBraier/WebRioAnchoColonia#9]
Fede, estoy viendo que no tenemos optimizados los nombres de las fotos del sitio. En cuanto puedas, poneles a así:

SECCIÓN INICIO

Mesa Gourmet - Río Ancho Colonia

SECCIÓN RÍO ANCHO:

Atardecer Río de la Plata- Río Ancho Colonia

Frente del Edificio- Río Ancho Colonia

Teteras y vasijas- Río Ancho Colonia

Martín Molteni Jefe de Cocina- Río Ancho Colonia

SECCIÓN MENÚ

Pescado Gourmet - Río Ancho Colonia

Carnes Gourmet - Río Ancho Colonia

Frutas silvestres - Río Ancho Colonia

Platos Agridulces - Río Ancho Colonia

Carne Jugosa - Río Ancho Colonia

SECCIÓN PROGRAMAS

Almuerzo mirando al Río de la Plata - Río Ancho Colonia

Té con vista al bosque- Río Ancho Colonia

Atardecer y tragos con vista al Río - Río Ancho Colonia

Cena Gourmet en Colonia - Río Ancho Colonia

Tazas de cerámica - Río Ancho Colonia

Living del Lodge - Río Ancho Colonia

Eventos corporativos - Río Ancho Colonia

abrazo

**Comment by FAAREIA** [comment]
Ahi ya le cambié los nombres lea, la palabra final "Río ancho colonia" la saqué, no hace falta, y ponerla en todos lados puede implicar una especie de spam

**Comment by LeandroBraier** [comment]
No no, al contrario, es para que funcione en buscadores de Google cuando alguien busca Río y Colonia. Ponela porfa, quién la podría considerar una especie de spam? Google? Ponela completa porfa, no te preocupes.

**Comment by FAAREIA** [comment]
Es que no es la forma, hay varias fotos que estan como fondo, a la cual uno no puede ponerle descripción. Las que si se puede, simplemente hay que poner lo que se ve, no más. La foto esta es un contexto no es un objeto individual en la web. No te preocupes que no hace falta y no esta bien ponerlo.

**Comment by LeandroBraier** [comment]
Vos decís que no aparecen en buscadores estas fotos? Si tienen una URL propia.

En tal caso deberíamos agregar una galería de fotos que sí lo levante google porque es una lástima perdernos el tráfico de gente que busca fotos de Colonia, de Restaurantes, etc.

**Comment by FAAREIA** [comment]
Las fotos que estan como fondo tengo entendido que rankean menos o no rankean.
Las fotos de fondo se usan para el efecto de parallax, todos esos plugins funcionan asi. Cambiar eso implicaría rehacer la mitad del sitio practicamente.
No creo que tampoco la gente se ponga a buscar fotos de Colonía y si lo hace, seguramente aparezcan otras primero, que tienen más antiguedad o que la gente clickea más porque son más "turisticas", hay 1350 factores para posicionar en google.
Lo más probable es que la gente busque algun restaurante de colonia y entre al sitio del restaurante, y ahi lo navegué y vea.
Más allá de todo igualmente, la foto tiene que tener la descripción de lo que se ve, no hace falta ponerle el nombre del sitio al costado, busca cualquier sitio y no lo hacen. La foto esta en un contexto y eso los buscadores lo interpretan, sino las búsquedas serían mucho menos exactas.

**Comment by LeandroBraier** [comment]
Ok. De todas formas creo que la gente busca fotos de Colonia y en la resolución que nosotros subimos no hay muchas. Quizá convenga pensar de otra manera esta estrategia, con algun perfil en Flickr por ejemplo, no a través del sitio. No te preocupes, dejemoslo así entonces.

Ya cierro este ticket.

abrazo
